'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, Banknote, Clock3, ShieldCheck, WalletCards } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { auth } from '@/lib/firebase';
import { getMyResellerProfile } from '@/lib/resellerLiveData';
import { MIN_WITHDRAWAL_AMOUNT } from '@/lib/resellerWallet';

export default function ResellerWalletPage() {
  const [available,setAvailable]=useState(0),[pending,setPending]=useState(0),[amount,setAmount]=useState(''),[method,setMethod]=useState('easypaisa'),[title,setTitle]=useState(''),[account,setAccount]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function load(){const user=auth.currentUser;if(!user)return;try{const token=await user.getIdToken();await fetch('/api/reseller/rewards/release',{method:'POST',headers:{Authorization:`Bearer ${token}`}});const profile=await getMyResellerProfile(user.uid);setAvailable(Number(profile?.walletAvailable||0));setPending(Number(profile?.walletPending||0));}catch(error){console.error(error);}}
  useEffect(()=>{load();},[]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const user=auth.currentUser;if(!user)throw new Error('Please sign in to withdraw.');const token=await user.getIdToken();const r=await fetch('/api/reseller/withdraw',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({amount:Number(amount),method,accountTitle:title,accountNumber:account})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Withdrawal request failed.');setMessage('Withdrawal request submitted. Admin will review it.');setAmount('');setTitle('');setAccount('');await load();}catch(error){setMessage(error instanceof Error?error.message:'Withdrawal request failed.');}finally{setBusy(false);}}
  return <main className="min-h-screen bg-[#F4F4F1] text-[#14140F]"><Header /><section className="bg-[#14140F] px-4 py-7 text-white sm:px-6"><div className="mx-auto max-w-3xl"><Link href="/reseller/dashboard" className="inline-flex items-center gap-2 text-[10px] font-bold text-white/60"><ArrowLeft size={13}/> Dashboard</Link><div className="mt-5 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#FFCF68]/10 text-[#FFCF68]"><WalletCards size={24}/></div><div><p className="text-[9px] font-black uppercase tracking-[0.2em] text-[#FFCF68]">Reseller Wallet</p><h1 className="text-2xl font-black">Rs. {available.toLocaleString()}</h1></div></div></div></section>
    <section className="mx-auto max-w-3xl space-y-4 px-4 py-6 sm:px-6"><div className="grid grid-cols-2 gap-3"><Balance label="Available" value={available}/><Balance label="Pending" value={pending}/></div>
      <form onSubmit={submit} className="rounded-[26px] bg-white p-5 shadow-[0_12px_35px_rgba(20,20,15,0.06)]"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-[#E1352B]">Withdraw</p><h2 className="mt-1 text-lg font-black">Request your available reward</h2><p className="mt-2 text-[10px] leading-5 text-black/45">Minimum withdrawal: Rs. {MIN_WITHDRAWAL_AMOUNT}. Admin approval is required before payment.</p><div className="mt-4 grid grid-cols-3 gap-2">{['easypaisa','jazzcash','bank'].map(item=><button type="button" key={item} onClick={()=>setMethod(item)} className={`rounded-2xl border p-3 text-[10px] font-black capitalize ${method===item?'border-[#0F6A5F] bg-[#0F6A5F]/10 text-[#0F6A5F]':'border-black/5 bg-[#F4F4F1]'}`}>{item}</button>)}</div><div className="mt-3 grid gap-3"><input required type="number" min={MIN_WITHDRAWAL_AMOUNT} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount (Rs.)" className="rounded-2xl border border-black/8 bg-[#F8F8F5] px-4 py-3 text-sm outline-none"/><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Account title" className="rounded-2xl border border-black/8 bg-[#F8F8F5] px-4 py-3 text-sm outline-none"/><input required value={account} onChange={e=>setAccount(e.target.value)} placeholder={method==='bank'?'Bank account / IBAN':'Mobile account number'} className="rounded-2xl border border-black/8 bg-[#F8F8F5] px-4 py-3 text-sm outline-none"/></div><button disabled={busy} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#14140F] py-3.5 text-sm font-black text-white disabled:opacity-50"><Banknote size={16}/>{busy?'Submitting…':'Request Withdrawal'}</button>{message&&<p className="mt-3 rounded-2xl bg-[#0F6A5F]/10 p-3 text-[10px] font-bold text-[#0F6A5F]">{message}</p>}</form>
      <div className="rounded-[24px] border border-[#0F6A5F]/10 bg-[#0F6A5F]/5 p-4"><div className="flex items-center gap-2 text-sm font-black"><ShieldCheck size={16} className="text-[#0F6A5F]"/> Protected wallet flow</div><div className="mt-3 space-y-2 text-[10px] text-black/50"><p className="flex items-center gap-2"><Clock3 size={13}/> Pending rewards are not withdrawable.</p><p className="flex items-center gap-2"><ShieldCheck size={13}/> Balance is reserved atomically when a withdrawal request is created.</p></div></div>
    </section><Footer /></main>;
}
function Balance({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white p-4 shadow-[0_10px_25px_rgba(20,20,15,0.04)]"><p className="text-[9px] font-black uppercase tracking-wider text-black/35">{label}</p><p className="mt-1 text-xl font-black">Rs. {value.toLocaleString()}</p></div>}
