'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, Banknote, Clock3, ShieldCheck, WalletCards, CheckCircle2, History, ChevronRight } from 'lucide-react';
import { auth } from '@/lib/firebase';
import { getMyResellerProfile } from '@/lib/resellerLiveData';
import { MIN_WITHDRAWAL_AMOUNT } from '@/lib/resellerWallet';

export default function ResellerWalletPage() {
  const [available,setAvailable]=useState(0),[pending,setPending]=useState(0),[amount,setAmount]=useState(''),[method,setMethod]=useState('easypaisa'),[title,setTitle]=useState(''),[account,setAccount]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function load(){const user=auth.currentUser;if(!user)return;try{const token=await user.getIdToken();await fetch('/api/reseller/rewards/release',{method:'POST',headers:{Authorization:`Bearer ${token}`}});const profile=await getMyResellerProfile(user.uid);setAvailable(Number(profile?.walletAvailable||0));setPending(Number(profile?.walletPending||0));}catch(error){console.error(error);}}
  useEffect(()=>{load();},[]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const user=auth.currentUser;if(!user)throw new Error('Please sign in to withdraw.');const token=await user.getIdToken();const r=await fetch('/api/reseller/withdraw',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({amount:Number(amount),method,accountTitle:title,accountNumber:account})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Withdrawal request failed.');setMessage('Withdrawal request submitted. Admin will review it.');setAmount('');setTitle('');setAccount('');await load();}catch(error){setMessage(error instanceof Error?error.message:'Withdrawal request failed.');}finally{setBusy(false);}}
  return <main className="min-h-screen bg-[#F4F4F1] text-[#14140F]"><section className="bg-gradient-to-br from-[#11130E] via-[#171A12] to-[#0F665B] px-4 pb-8 pt-5 text-white sm:px-6"><div className="mx-auto max-w-3xl"><Link href="/reseller/dashboard" className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3.5 py-2 text-[10px] font-black text-white/75 ring-1 ring-white/10"><ArrowLeft size={13}/> Dashboard</Link><div className="mt-6 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#FFCF68] text-[#14140F] shadow-[0_10px_30px_rgba(255,207,104,.18)]"><WalletCards size={23}/></div><div><p className="text-[9px] font-black uppercase tracking-[0.22em] text-[#FFCF68]">Reseller Wallet</p><h1 className="mt-1 text-2xl font-black">Reward Wallet</h1><p className="mt-1 text-[10px] text-white/55">Earned from eligible PrimeHub activity</p></div></div><div className="mt-6 grid grid-cols-2 gap-3"><HeroBalance label="Available to withdraw" value={`Rs. ${available.toLocaleString()}`} /><HeroBalance label="Pending" value={`Rs. ${pending.toLocaleString()}`} /></div></div></section>
    <section className="mx-auto max-w-3xl space-y-4 px-4 py-6 sm:px-6"><form onSubmit={submit} className="rounded-[28px] bg-white p-5 shadow-[0_14px_38px_rgba(20,20,15,.06)] ring-1 ring-black/[.03]"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[0.2em] text-[#E1352B]">Withdraw reward</p><h2 className="mt-1 text-xl font-black">Turn your balance into cash</h2><p className="mt-2 text-[10px] leading-5 text-black/45">Minimum withdrawal Rs. {MIN_WITHDRAWAL_AMOUNT}. Admin approval is required before payment.</p></div><Banknote className="text-[#0F6A5F]" size={22}/></div><div className="mt-5 grid grid-cols-3 gap-2">{['easypaisa','jazzcash','bank'].map(item=><button type="button" key={item} onClick={()=>setMethod(item)} className={`rounded-2xl border p-3 text-[10px] font-black capitalize transition ${method===item?'border-[#0F6A5F] bg-[#DDF5F0] text-[#0F6A5F] shadow-sm':'border-black/5 bg-[#F4F4F1]'}`}>{item}</button>)}</div><div className="mt-3 grid gap-3"><input required type="number" min={MIN_WITHDRAWAL_AMOUNT} max={available} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Amount (Rs.)" className="rounded-2xl border border-black/8 bg-[#F8F8F5] px-4 py-3.5 text-sm outline-none focus:border-[#0F6A5F]"/><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Account title" className="rounded-2xl border border-black/8 bg-[#F8F8F5] px-4 py-3.5 text-sm outline-none focus:border-[#0F6A5F]"/><input required value={account} onChange={e=>setAccount(e.target.value)} placeholder={method==='bank'?'Bank account / IBAN':'Mobile account number'} className="rounded-2xl border border-black/8 bg-[#F8F8F5] px-4 py-3.5 text-sm outline-none focus:border-[#0F6A5F]"/></div><button disabled={busy||available<MIN_WITHDRAWAL_AMOUNT} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#14140F] py-3.5 text-sm font-black text-white disabled:opacity-45"><Banknote size={16}/>{busy?'Submitting…':available<MIN_WITHDRAWAL_AMOUNT?'Minimum balance not reached':'Request Withdrawal'}</button>{message&&<div className="mt-3 flex items-center gap-2 rounded-2xl bg-[#0F6A5F]/10 p-3 text-[10px] font-bold text-[#0F6A5F]"><CheckCircle2 size={15}/>{message}</div>}</form>
      <div className="rounded-[26px] bg-white p-5 shadow-[0_12px_35px_rgba(20,20,15,.05)]"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><History size={16} className="text-[#0F6A5F]"/><h2 className="text-sm font-black">Wallet Activity</h2></div><ChevronRight size={16} className="text-black/20"/></div><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="Available" value={`Rs. ${available.toLocaleString()}`} /><Mini label="Pending" value={`Rs. ${pending.toLocaleString()}`} /><Mini label="Min. withdrawal" value={`Rs. ${MIN_WITHDRAWAL_AMOUNT}`} /></div><p className="mt-4 text-[9px] leading-4 text-black/40">Detailed reward and withdrawal history will populate here as confirmed reseller orders and approved payouts are connected.</p></div>
      <div className="rounded-[24px] border border-[#0F6A5F]/10 bg-[#0F6A5F]/5 p-4"><div className="flex items-center gap-2 text-sm font-black"><ShieldCheck size={16} className="text-[#0F6A5F]"/> Protected wallet flow</div><div className="mt-3 space-y-2 text-[10px] text-black/50"><p className="flex items-center gap-2"><Clock3 size={13}/> Pending rewards cannot be withdrawn.</p><p className="flex items-center gap-2"><ShieldCheck size={13}/> Balance is reserved atomically when a withdrawal request is created.</p></div></div>
    </section></main>;
}

function HeroBalance({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white/10 p-3 ring-1 ring-white/10"><p className="text-[8px] font-black uppercase tracking-wider text-white/45">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-[#F4F4F1] p-3"><p className="text-[8px] font-black uppercase tracking-wider text-black/35">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>}
