'use client';

import { useEffect, useMemo, useState } from 'react';
import { onAuthStateChanged, User } from 'firebase/auth';
import { collection, doc, onSnapshot, runTransaction, serverTimestamp } from 'firebase/firestore';
import { Gift, Sparkles, Trophy, Zap, LogIn, Lock, RotateCw } from 'lucide-react';
import { auth, db } from '@/lib/firebase';

type Prize={name:string;type:'try-again'|'points'|'coupon'|'free-delivery';points:number;probability:number;active?:boolean;voucherCode?:string;imageUrl?:string};
type RewardSettings={dailySpinLimit:number;checkInRewards:number[];guestMode:boolean;loginRequiredToRedeem:boolean;pointsExpiryDays:number;spinWheelSlots?:Prize[]};
type Wallet={points:number;streak:number;lastCheckIn?:string;lastSpin?:string;coupons?:string[]};
const GUEST_KEY='phdeals-guest-rewards';
const defaultSettings:RewardSettings={dailySpinLimit:1,checkInRewards:[10,15,20,25,30,50,100],guestMode:true,loginRequiredToRedeem:true,pointsExpiryDays:0};
const emptyWallet:Wallet={points:0,streak:0,coupons:[]};
function day(){return new Date().toISOString().slice(0,10)}
function weighted(prizes:Prize[]){const active=prizes.filter(p=>p.active!==false&&Number(p.probability)>0);const total=active.reduce((n,p)=>n+Number(p.probability),0);let r=Math.random()*total;for(const p of active){r-=Number(p.probability);if(r<=0)return p}return active[active.length-1]}
function prizeLabel(p:Prize){if(p.type==='try-again')return 'TRY AGAIN';if(p.type==='points')return `${p.points} PTS`;if(p.type==='free-delivery')return 'FREE DELIVERY';return 'VOUCHER'}

export default function RewardsPage(){
 const [user,setUser]=useState<User|null>(null);const [ready,setReady]=useState(false);const [wallet,setWallet]=useState<Wallet>(emptyWallet);const [settings,setSettings]=useState(defaultSettings);const [prizes,setPrizes]=useState<Prize[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [spinning,setSpinning]=useState(false);const [rotation,setRotation]=useState(0);
 useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setReady(true)}),[]);
 useEffect(()=>{const a=onSnapshot(doc(db,'settings','rewards'),s=>{const d=s.data()||{};setSettings({...defaultSettings,...d});setPrizes(Array.isArray(d.spinWheelSlots)?d.spinWheelSlots:[])});return()=>a()},[]);
 useEffect(()=>{if(user){return onSnapshot(doc(db,'user_rewards',user.uid),s=>setWallet({...emptyWallet,...(s.data()||{})} as Wallet))}try{const s=localStorage.getItem(GUEST_KEY);if(s)setWallet({...emptyWallet,...JSON.parse(s)})}catch{}},[user]);
 const saveGuest=(w:Wallet)=>{setWallet(w);try{localStorage.setItem(GUEST_KEY,JSON.stringify(w))}catch{}};
 const activePrizes=useMemo(()=>prizes.filter(p=>p.active!==false),[prizes]);
 async function checkIn(){if(wallet.lastCheckIn===day())return;setBusy(true);try{const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);const streak=wallet.lastCheckIn===yesterday?Math.min(7,Math.max(1,wallet.streak)+1):1;const points=Number(settings.checkInRewards[streak-1]??10);const next={...wallet,points:wallet.points+points,streak,lastCheckIn:day()};if(user)await runTransaction(db,async tx=>{const ref=doc(db,'user_rewards',user.uid);const snap=await tx.get(ref);const current={...emptyWallet,...(snap.data()||{})} as Wallet;if(current.lastCheckIn===day())throw new Error('Already checked in today.');tx.set(ref,{...current,points:Number(current.points)+points,streak,lastCheckIn:day(),updatedAt:serverTimestamp()},{merge:true})});else saveGuest(next);setMessage(`Day ${streak} complete — +${points} points`)}catch(e){setMessage(e instanceof Error?e.message:'Check-in failed')}finally{setBusy(false)}}
 async function spin(){if(wallet.lastSpin===day()||settings.dailySpinLimit<1||spinning)return;setBusy(true);setSpinning(true);setMessage('');try{const prize=weighted(activePrizes);if(!prize)throw new Error('Spin prizes are not configured yet.');const prizeIndex=Math.max(0,activePrizes.indexOf(prize));const slice=360/Math.max(1,activePrizes.length);const target=360*5+(360-(prizeIndex*slice+slice/2));setRotation(r=>r+target);const gained=Math.max(0,Number(prize.points||0));const coupon=prize.type==='coupon'?(prize.voucherCode||`PH-${Math.random().toString(36).slice(2,8).toUpperCase()}`):'';if(user)await runTransaction(db,async tx=>{const ref=doc(db,'user_rewards',user.uid);const snap=await tx.get(ref);const current={...emptyWallet,...(snap.data()||{})} as Wallet;if(current.lastSpin===day())throw new Error('Come back tomorrow.');tx.set(ref,{...current,points:Number(current.points)+gained,lastSpin:day(),coupons:coupon?[...(current.coupons||[]),coupon]:(current.coupons||[]),updatedAt:serverTimestamp()},{merge:true})});else saveGuest({...wallet,points:wallet.points+gained,lastSpin:day(),coupons:coupon?[...(wallet.coupons||[]),coupon]:(wallet.coupons||[])});window.setTimeout(()=>setMessage(prize.type==='try-again'?'Try again tomorrow — better luck next time!':`🎉 ${prize.name} — ${gained?`+${gained} points`:coupon||'Reward won!'}`),900)}catch(e){setMessage(e instanceof Error?e.message:'Spin failed');setSpinning(false);setBusy(false);return}window.setTimeout(()=>{setSpinning(false);setBusy(false)},1000)}
 if(!ready)return <main className="min-h-screen bg-[#F4F4F1]"/>;
 const wheelCount=Math.max(1,activePrizes.length);const slice=360/wheelCount;
 return <main className="min-h-screen bg-[#F4F4F1] px-4 py-6 pb-28"><div className="mx-auto max-w-md space-y-4"><section className="rounded-[30px] bg-[#14140F] p-6 text-white shadow-md"><Sparkles className="h-6 w-6 text-[#FFB020]"/><h1 className="mt-3 text-3xl font-black">Rewards Hub</h1><p className="mt-2 text-xs text-white/60">{user?.email||'Guest rewards — no account required'}</p><p className="mt-5 text-3xl font-black text-[#FFB020]">{wallet.points||0} points</p>{!user&&<a href="/login" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-xs font-black text-black"><LogIn size={14}/>Login to save rewards</a>}</section>
 <section className="rounded-[30px] border bg-white p-5 shadow-sm"><Trophy className="h-6 w-6 text-[#E1352B]"/><h2 className="mt-2 text-xl font-black">7-Day Check-in</h2><p className="mt-1 text-xs text-black/45">Complete each day to collect the exact points shown below.</p><div className="mt-4 grid grid-cols-7 gap-1">{Array.from({length:7},(_,i)=><div key={i} className={`rounded-lg p-2 text-center ${i<Number(wallet.streak||0)?'bg-[#0F6A5F] text-white':'bg-[#F4F4F1] text-black/45'}`}><div className="text-[8px] font-black">D{i+1}</div><div className="mt-1 text-[9px] font-black">+{Number(settings.checkInRewards[i]??0)}</div><div className="text-[7px] font-bold">PTS</div></div>)}</div><button disabled={busy||wallet.lastCheckIn===day()} onClick={checkIn} className="mt-4 w-full rounded-xl bg-[#14140F] py-3 text-xs font-black text-white disabled:opacity-50">{wallet.lastCheckIn===day()?'Checked in today':`Check in +${settings.checkInRewards[Math.max(0,Math.min(6,wallet.streak||0))]??10} points`}</button></section>
 <section className="rounded-[30px] border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Zap className="h-6 w-6 text-[#FFB020]"/><h2 className="text-xl font-black">Spin & Win</h2></div><p className="mt-1 text-xs text-black/45">A real prize wheel. Try Again and small points can be common; big prizes stay rare using your admin probabilities.</p><div className="relative mx-auto mt-5 h-72 w-72 max-w-full"><div className="absolute -top-2 left-1/2 z-20 -translate-x-1/2 text-[#E1352B]">▼</div><div className="absolute inset-0 rounded-full border-[10px] border-[#14140F] bg-white shadow-xl" style={{transform:`rotate(${rotation}deg)`,transition:spinning?'transform 1.8s cubic-bezier(.12,.7,.18,1)':'none'}}><div className="absolute inset-3 overflow-hidden rounded-full" style={{background:`conic-gradient(${activePrizes.map((_,i)=>`${i%2?'#FFF1D6':'#F4F4F1'} ${i*slice}deg ${(i+1)*slice}deg`).join(',')||'#F4F4F1 0deg 360deg'})`}}>{activePrizes.map((p,i)=><div key={`${p.name}-${i}`} className="absolute left-1/2 top-1/2 h-1/2 w-[42%] origin-bottom -translate-x-1/2 -translate-y-full text-center" style={{transform:`translateX(-50%) rotate(${i*slice+slice/2}deg)`}}><div className="mx-auto flex h-10 w-10 -translate-y-1 items-center justify-center overflow-hidden rounded-full bg-white shadow-sm">{p.imageUrl?<img src={p.imageUrl} alt="" className="h-full w-full object-cover"/>:<span className="text-[8px] font-black">{p.points||'★'}</span>}</div><span className="mt-1 block text-[7px] font-black leading-3">{prizeLabel(p)}</span></div>)}</div><div className="absolute left-1/2 top-1/2 z-10 flex h-14 w-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border-4 border-white bg-[#E1352B] text-white shadow-lg"><RotateCw size={20}/></div></div></div><button disabled={busy||wallet.lastSpin===day()||!activePrizes.length} onClick={spin} className="mt-5 w-full rounded-xl bg-[#E1352B] py-4 text-xs font-black text-white disabled:opacity-50">{wallet.lastSpin===day()?'Come back tomorrow':spinning?'Spinning...':'SPIN THE WHEEL'}</button></section>
 {message&&<p className="rounded-xl bg-[#0F6A5F] p-3 text-center text-xs font-black text-white">{message}</p>}<div className="flex items-center justify-center gap-1 text-[9px] font-bold text-black/35"><Lock size={11}/> Login saves your points permanently; guest mode uses this device.</div></div></main>;
}
