'use client';
import { ImagePlus, Loader2 } from 'lucide-react';
import type { BucketFormProps } from './CategoryTypes';
export default function BucketForm({ bucketForm, editingBucketId, isSaving, uploading, onChange, onOpenGallery, onUploadDevice, onSubmit, onCancel }: BucketFormProps) {
  return <form onSubmit={onSubmit} className="mt-5 rounded-2xl border border-black/10 bg-white p-5">
    <div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-semibold">Bucket name<input value={bucketForm.title} onChange={(e) => onChange((c) => ({ ...c, title: e.target.value }))} placeholder="Under 500" required className="mt-1.5 w-full rounded-lg border border-black/15 px-3 py-2 text-sm" /></label><label className="text-xs font-semibold">Maximum price (Rs.)<input type="number" min="0" value={bucketForm.amount || ''} onChange={(e) => onChange((c) => ({ ...c, amount: Number(e.target.value) }))} placeholder="500" required className="mt-1.5 w-full rounded-lg border border-black/15 px-3 py-2 text-sm" /></label></div>
    <div className="mt-3 text-xs font-semibold"><span>Bucket icon</span><div className="mt-1.5 flex flex-wrap items-center gap-2"><button type="button" onClick={onOpenGallery} className="inline-flex items-center gap-2 rounded-lg border border-black/15 px-3 py-2 text-xs font-black"><ImagePlus size={14} /> Media Gallery</button><button type="button" disabled={uploading} onClick={onUploadDevice} className="inline-flex items-center gap-2 rounded-lg bg-[#14140F] px-3 py-2 text-xs font-black text-white disabled:opacity-50"><ImagePlus size={14} /> {uploading ? 'Uploading...' : 'Upload from device'}</button>{bucketForm.iconUrl && <img src={bucketForm.iconUrl} alt="Selected" className="h-10 w-10 rounded-lg object-cover" />}</div></div>
    <div className="mt-3 flex items-center gap-3"><label className="text-xs font-semibold">Accent<input type="text" value={bucketForm.accent} onChange={(e) => onChange((c) => ({ ...c, accent: e.target.value }))} className="ml-2 w-28 rounded-lg border border-black/15 px-3 py-2 text-xs" /></label><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={bucketForm.active} onChange={(e) => onChange((c) => ({ ...c, active: e.target.checked }))} /> Active on storefront</label></div>
    <div className="mt-4 flex gap-2"><button type="submit" disabled={isSaving || uploading} className="flex-1 rounded-lg bg-[#14140F] px-5 py-2.5 text-sm font-semibold text-white">{isSaving ? <Loader2 className="mx-auto h-4 w-4 animate-spin" /> : editingBucketId ? 'Save Price Bucket' : 'Create Price Bucket'}</button>{editingBucketId && <button type="button" onClick={onCancel} className="rounded-lg border border-black/10 px-5 py-2.5 text-sm font-semibold">Cancel</button>}</div>
  </form>;
}
