'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { ArrowRight,Sparkles } from 'lucide-react';
import { collection,onSnapshot } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { imageOf,priceOf,titleOf,type Product } from '@/components/shop/ShopTypes';
function timeOf(p:Product){const value=p.createdAt||p.updatedAt;return typeof value?.toMillis==='function'?value.toMillis():new Date(value||0).getTime()||0}
export function newestFirst(products:Product[]){return [...products].filter(p=>p.published!==false).sort((a,b)=>timeOf(b)-timeOf(a)||b.id.localeCompare(a.id))}
export default function NewArrivalsRail(){const[products,setProducts]=useState<Product[]>([]);useEffect(()=>onSnapshot(collection(db,'products'),s=>setProducts(s.docs.map(d=>({id:d.id,...d.data()}) as Product))),[]);const newest=useMemo(()=>newestFirst(products).slice(0,10),[products]);if(!newest.length)return null;return <section className="mt-5"><div className="mb-3 flex items-end justify-between px-4"><div><div className="flex items-center gap-1 text-[#B7791F]"><Sparkles size={12}/><span className="text-[8px] font-black uppercase tracking-[.2em]">Premium Picks</span></div><h2 className="mt-1 text-xl font-black">New Arrivals</h2></div><Link href="/new-arrivals" className="flex items-center gap-1 rounded-full bg-[#14140F] px-3 py-2 text-[9px] font-black text-white">View All <ArrowRight size={12}/></Link></div><div className="flex snap-x gap-2.5 overflow-x-auto px-4 pb-3 [scrollbar-width:none] lg:[scrollbar-width:thin] lg:[scrollbar-color:#9ca3af_transparent] [&::-webkit-scrollbar]:hidden lg:[&::-webkit-scrollbar]:block lg:[&::-webkit-scrollbar]:h-1.5 lg:[&::-webkit-scrollbar-thumb]:rounded-full lg:[&::-webkit-scrollbar-thumb]:bg-black/25">{newest.map(p=><Link key={p.id} href={'/product/'+p.id} className="w-[132px] shrink-0 snap-start overflow-hidden rounded-[18px] bg-white shadow-sm ring-1 ring-black/5 sm:w-[150px]"><div className="relative aspect-square overflow-hidden bg-white">{imageOf(p)?<img src={imageOf(p)} alt={titleOf(p)} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-[9px] text-black/30">No image</div>}<span className="absolute left-1.5 top-1.5 rounded-full bg-gradient-to-r from-[#A66A00] to-[#F6C453] px-2 py-1 text-[7px] font-black uppercase tracking-wider text-white shadow">New Arrival</span></div><div className="p-2.5"><p className="line-clamp-2 min-h-[28px] text-[10px] font-black leading-[14px]">{titleOf(p)}</p><p className="mt-1 text-[11px] font-black text-[#E1352B]">Rs. {priceOf(p).toLocaleString()}</p></div></Link>)}</div></section>}