'use client';
import { useMemo } from 'react';
import { useShopCatalog } from './shop/useShopCatalog';
import CatalogHeader from './shop/CatalogHeader';
import BudgetBuckets from './shop/BudgetBuckets';
import CategoryFilter from './shop/CategoryFilter';
import { FilterDrawer } from './shop/CatalogFilters';
import CatalogProductGrid from './shop/CatalogProductGrid';
import CompactCategoryStrip from './shop/CompactCategoryStrip';
function score(id:string){return Array.from(id).reduce((n,c)=>((n*31+c.charCodeAt(0))>>>0),7)}
export default function ShopCatalog({initialCategory,initialQuery=''}:{initialCategory?:string;initialQuery?:string}){const shop=useShopCatalog(initialCategory,initialQuery);const categoryView=Boolean(initialCategory);const picks=useMemo(()=>[...shop.filtered].sort((a,b)=>score(a.id)-score(b.id)),[shop.filtered]);const clearAll=()=>{shop.setSearch('');shop.setCategory(initialCategory||'all');shop.setMaxPrice('all');shop.setOnlyDeals(false);shop.setWholesaleOnly(false);shop.setFiltersOpen(false)};return <main className="min-h-screen bg-[#F4F4F1] pb-28"><div className="mx-auto max-w-6xl px-4 py-5 md:px-6"><CatalogHeader search={shop.search} count={shop.filtered.length} setSearch={shop.setSearch} title={categoryView?shop.categoryLabel:undefined} setFiltersOpen={shop.setFiltersOpen} onlyDeals={shop.onlyDeals} setOnlyDeals={shop.setOnlyDeals}/>{!categoryView&&<CompactCategoryStrip categories={shop.categories}/>}<BudgetBuckets buckets={shop.buckets} maxPrice={shop.maxPrice} setMaxPrice={shop.setMaxPrice} wholesaleOnly={shop.wholesaleOnly} setWholesaleOnly={shop.setWholesaleOnly}/>{categoryView&&<CategoryFilter categories={shop.categories} category={shop.category} setCategory={shop.setCategory}/>}<section className="mt-6"><div className="mb-3"><p className="text-[9px] font-black uppercase tracking-[0.2em] text-[#E1352B]">{categoryView?'Category products':'Picked for you'}</p><h2 className="mt-0.5 text-xl font-black tracking-tight">{categoryView?shop.categoryLabel:'✨ Just For You'}</h2></div><CatalogProductGrid products={categoryView?shop.filtered:picks} addedId={shop.addedId} addProduct={shop.addProduct} loading={shop.loading} dense={!categoryView}/></section></div><FilterDrawer filtersOpen={shop.filtersOpen} setFiltersOpen={shop.setFiltersOpen} maxPrice={shop.maxPrice} setMaxPrice={shop.setMaxPrice} onlyDeals={shop.onlyDeals} setOnlyDeals={shop.setOnlyDeals} clearAll={clearAll}/></main>}