import { SlidersHorizontal, X } from 'lucide-react';

type Props = { filtersOpen: boolean; setFiltersOpen: (value: boolean) => void; maxPrice: string; setMaxPrice: (value: string) => void; onlyDeals: boolean; setOnlyDeals: (value: boolean | ((v: boolean) => boolean)) => void; clearAll: () => void };
export function FilterDrawer({ filtersOpen, setFiltersOpen, maxPrice, setMaxPrice, onlyDeals, setOnlyDeals, clearAll }: Props) {
  if (!filtersOpen) return null;
  return <div className="fixed inset-0 z-[100]"><button type="button" className="absolute inset-0 bg-black/50" onClick={() => setFiltersOpen(false)} aria-label="Close filters" /><div className="absolute bottom-0 left-0 right-0 rounded-t-[30px] bg-white p-5 shadow-2xl md:left-1/2 md:right-auto md:top-1/2 md:w-[420px] md:-translate-x-1/2 md:-translate-y-1/2 md:rounded-[30px]"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[0.2em] text-[#E1352B]">Refine</p><h2 className="mt-1 text-lg font-black">Shop Filters</h2></div><button type="button" onClick={() => setFiltersOpen(false)} className="flex h-9 w-9 items-center justify-center rounded-full bg-[#F4F4F1]"><X size={15} /></button></div><div className="mt-6"><p className="text-[10px] font-black uppercase tracking-wider text-black/40">Price</p><div className="mt-2 grid grid-cols-4 gap-2">{[['all','Any'],['99','Under 99'],['499','Under 499'],['999','Under 999']].map(([value,label]) => <button key={value} type="button" onClick={() => setMaxPrice(value)} className={`rounded-2xl px-2 py-3 text-[9px] font-black ${maxPrice === value ? 'bg-[#14140F] text-white' : 'bg-[#F4F4F1] text-[#14140F]'}`}>{label}</button>)}</div></div><button type="button" onClick={() => setOnlyDeals((v) => !v)} className={`mt-4 flex w-full items-center justify-between rounded-2xl p-4 text-left ${onlyDeals ? 'bg-[#E1352B] text-white' : 'bg-[#F4F4F1] text-[#14140F]'}`}><span><span className="block text-[11px] font-black">Flash Deals only</span><span className="mt-0.5 block text-[9px] opacity-60">Show products marked as flash sales</span></span><span className="text-[10px] font-black">{onlyDeals ? 'ON' : 'OFF'}</span></button><button type="button" onClick={clearAll} className="mt-4 w-full rounded-full bg-[#14140F] py-3 text-[10px] font-black text-white">Clear all filters</button></div></div>;
}

type BarProps = { setFiltersOpen: (value: boolean) => void; onlyDeals: boolean; setOnlyDeals: (value: boolean | ((v: boolean) => boolean)) => void };
export default function CatalogFilters({ setFiltersOpen, onlyDeals, setOnlyDeals }: BarProps) {
  return <div className="mt-5 flex items-center justify-between gap-2"><button type="button" onClick={() => setFiltersOpen(true)} className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-[10px] font-black shadow-sm ring-1 ring-black/5"><SlidersHorizontal size={14} /> Filters</button><button type="button" onClick={() => setOnlyDeals((v) => !v)} className={`rounded-2xl px-4 py-3 text-[10px] font-black shadow-sm ring-1 ring-black/5 ${onlyDeals ? 'bg-[#E1352B] text-white' : 'bg-white text-[#14140F]'}`}>Flash deals only</button></div>;
}
