'use client';
import { FormEvent, useMemo, useState } from 'react';
import { useCartStore } from '@/lib/cartStore';
import type { Customer } from './CheckoutTypes';
export const titleOf=(i:any)=>i.title||i.name||'Product';
export const priceOf=(i:any)=>Number(i.price||0);
export const imageOf=(i:any)=>i.imageUrl||i.image||i.images?.[0]||'';
export async function getAuthoritativeQuote(items:any[]){const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'quote',items})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to verify current prices.');return d;}
export function useCheckout(){const items=useCartStore((s:any)=>s.items||s.cart||[]);const clearCart=useCartStore((s:any)=>s.clearCart);const [customer,setCustomer]=useState<Customer>({name:'',phone:'',email:'',address:'',city:'',notes:''});const [placing,setPlacing]=useState(false),[orderId,setOrderId]=useState(''),[error,setError]=useState('');const totalItems=useMemo(()=>items.reduce((s:number,i:any)=>s+Number(i.quantity||i.qty||1),0),[items]);const subtotal=useMemo(()=>items.reduce((s:number,i:any)=>s+priceOf(i)*Number(i.quantity||i.qty||1),0),[items]);const update=(key:keyof Customer,value:string)=>setCustomer(p=>({...p,[key]:value}));const placeOrder=async(e:FormEvent)=>{e.preventDefault();setError('');if(!items.length)return setError('Your cart is empty. Please add a product first.');if(!customer.name.trim()||!customer.phone.trim()||!customer.address.trim()||!customer.city.trim())return setError('Please fill your name, phone, address and city.');setPlacing(true);try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer,items})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Order save nahi ho saka.');setOrderId(d.orderId);clearCart();}catch(err){console.error(err);setError(err instanceof Error?err.message:'Order save nahi ho saka. Please try again.');}finally{setPlacing(false);}};const whatsappOrder=async()=>{if(!items.length)return;setError('');try{const q=await getAuthoritativeQuote(items);const lines=q.items.map((i:any,n:number)=>`${n+1}. ${i.title} × ${i.quantity} — Rs. ${(Number(i.price)*Number(i.quantity)).toLocaleString()}`);const text=['🛍️ PrimeHub Deals Order','',...lines,'',`Customer: ${customer.name||'-'}`,`Phone: ${customer.phone||'-'}`,`City: ${customer.city||'-'}`,`Address: ${customer.address||'-'}`,`Total: Rs. ${Number(q.subtotal).toLocaleString()}`].join('\n');window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer');}catch(err){setError(err instanceof Error?err.message:'Unable to verify current prices.');}};return{items,customer,placing,orderId,error,totalItems,subtotal,update,placeOrder,whatsappOrder};}
