/** Global persistent cart state. */
import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import type { ProductVariantSelection, Weekday } from '@/lib/types';
export const FREE_DELIVERY_THRESHOLD=5;
export interface CartItem{id:string|number;name:string;price:number;originalPrice:number;image?:string;imageUrl?:string;qty:number;dealDay?:Weekday;productId?:string;variant?:ProductVariantSelection;}
interface CartState{items:CartItem[];isDrawerOpen:boolean;isMiniCollapsed:boolean;addItem:(item:Omit<CartItem,'qty'>)=>void;removeItem:(id:string|number)=>void;updateQty:(id:string|number,qty:number)=>void;clearCart:()=>void;openDrawer:()=>void;closeDrawer:()=>void;minimizeCart:()=>void;expandMiniCart:()=>void;toggleDrawer:()=>void;getCartCount:()=>number;getSubtotal:()=>number;getItemsToFreeDelivery:()=>number;getDeliveryProgress:()=>number;}
function variantKey(variant?:ProductVariantSelection){return variant?Object.entries(variant).filter(([,v])=>v).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}:${v}`).join('|'):'';}
function resolveVisibleProductImage(item:Omit<CartItem,'qty'>){if(item.image||item.imageUrl||typeof document==='undefined')return item.image||item.imageUrl||'';const match=Array.from(document.images).find(i=>i.alt.trim().toLowerCase()===item.name.trim().toLowerCase());return match?.currentSrc||match?.src||'';}
export const useCartStore=create<CartState>()(persist((set,get)=>({items:[],isDrawerOpen:false,isMiniCollapsed:false,addItem:item=>{const resolvedImage=resolveVisibleProductImage(item),normalized={...item,id:item.id||`${item.productId||''}:${variantKey(item.variant)}`,image:item.image||item.imageUrl||resolvedImage,imageUrl:item.imageUrl||item.image||resolvedImage};set(state=>{const existing=state.items.find(i=>i.id===normalized.id);return{items:existing?state.items.map(i=>i.id===normalized.id?{...i,...normalized,qty:i.qty+1}:i):[...state.items,{...normalized,qty:1}],isDrawerOpen:true,isMiniCollapsed:false};});},removeItem:id=>set(s=>({items:s.items.filter(i=>i.id!==id)})),updateQty:(id,qty)=>set(s=>({items:qty<=0?s.items.filter(i=>i.id!==id):s.items.map(i=>i.id===id?{...i,qty}:i)})),clearCart:()=>set({items:[],isDrawerOpen:false,isMiniCollapsed:false}),openDrawer:()=>set({isDrawerOpen:true,isMiniCollapsed:false}),closeDrawer:()=>set({isDrawerOpen:false}),minimizeCart:()=>set({isDrawerOpen:false,isMiniCollapsed:true}),expandMiniCart:()=>set({isDrawerOpen:true,isMiniCollapsed:false}),toggleDrawer:()=>set(s=>({isDrawerOpen:!s.isDrawerOpen,isMiniCollapsed:s.isDrawerOpen?s.isMiniCollapsed:false})),getCartCount:()=>get().items.reduce((s,i)=>s+i.qty,0),getSubtotal:()=>get().items.reduce((s,i)=>s+i.price*i.qty,0),getItemsToFreeDelivery:()=>Math.max(0,FREE_DELIVERY_THRESHOLD-get().items.reduce((s,i)=>s+i.qty,0)),getDeliveryProgress:()=>Math.min(100,Math.round(get().items.reduce((s,i)=>s+i.qty,0)/FREE_DELIVERY_THRESHOLD*100))}),{name:'phdeals-cart',storage:createJSONStorage(()=>localStorage),partialize:s=>({items:s.items})}));
