/** Global persistent cart state + global variant selector trigger. */
import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';
import type { ProductVariantRow, ProductVariantSelection, Weekday } from '@/lib/types';
export const FREE_DELIVERY_THRESHOLD=5;
type VariantModalImage=string|{url?:string}|Record<string,unknown>;
export interface CartItem{id:string|number;name:string;price:number;originalPrice:number;image?:string;imageUrl?:string;qty:number;dealDay?:Weekday;productId?:string;variant?:ProductVariantSelection;}
export interface VariantModalProduct{id:string;title?:string;name?:string;price?:number;originalPrice?:number;compareAtPrice?:number;imageUrl?:string;image?:string;images?:VariantModalImage[];variantMatrix?:ProductVariantRow[];variants?:ProductVariantRow[];variantColors?:Array<{name:string;imageUrl?:string}>|string[];variantSizes?:string[];colors?:string[];sizes?:string[];variantOptions?:Array<{id:string;values:string[]}>;hasVariants?:boolean;colorImages?:Record<string,string>;[key:string]:unknown;}
interface CartState{items:CartItem[];isDrawerOpen:boolean;isMiniCollapsed:boolean;variantModalProduct:VariantModalProduct|null;variantModalMode:'cart'|'buy'|null;addItem:(item:Omit<CartItem,'qty'>)=>void;removeItem:(id:string|number)=>void;updateQty:(id:string|number,qty:number)=>void;clearCart:()=>void;openDrawer:()=>void;closeDrawer:()=>void;minimizeCart:()=>void;expandMiniCart:()=>void;toggleDrawer:()=>void;openVariantModal:(product:VariantModalProduct,mode:'cart'|'buy')=>boolean;closeVariantModal:()=>void;getCartCount:()=>number;getSubtotal:()=>number;getItemsToFreeDelivery:()=>number;getDeliveryProgress:()=>number;}
function asStrings(value:unknown):string[]{if(!Array.isArray(value))return[];return value.map(item=>{if(typeof item==='string'||typeof item==='number')return String(item).trim();if(item&&typeof item==='object'){const r=item as Record<string,unknown>;const v=r.name??r.value??r.label??r.title;return typeof v==='string'||typeof v==='number'?String(v).trim():'';}return'';}).filter(Boolean);}
function rowValue(row:ProductVariantRow,key:'color'|'size'):string{const r=row as Record<string,unknown>;const direct=r[key]??r[`variant${key[0].toUpperCase()}${key.slice(1)}`];if(typeof direct==='string'||typeof direct==='number')return String(direct).trim();if(r.options&&typeof r.options==='object'){const options=r.options as Record<string,unknown>;const value=options[key];if(typeof value==='string'||typeof value==='number')return String(value).trim();}return'';}
function variantRows(product:VariantModalProduct):ProductVariantRow[]{
 const direct=Array.isArray(product.variants)?product.variants:[];const matrix=Array.isArray(product.variantMatrix)?product.variantMatrix:[];const source=[...direct,...matrix];
 const rowColors=source.map(r=>rowValue(r,'color')).filter(Boolean),rowSizes=source.map(r=>rowValue(r,'size')).filter(Boolean);
 const colorValues=[...asStrings(product.variantColors),...asStrings(product.colors),...rowColors];const sizeValues=[...asStrings(product.variantSizes),...asStrings(product.sizes),...rowSizes];
 colorValues.push(...asStrings(product.variantOptions?.find(o=>/color/i.test(String(o.id)))?.values));sizeValues.push(...asStrings(product.variantOptions?.find(o=>/size/i.test(String(o.id)))?.values));
 const colors=[...new Set(colorValues)],sizes=[...new Set(sizeValues)];
 if(source.length){const fallbackColor=colors.length?colors[0]:'Standard',fallbackSize=sizes.length?sizes[0]:'Standard';return source.map((row,index)=>{const color=rowValue(row,'color')||fallbackColor;const size=rowValue(row,'size')||fallbackSize;return{...row,id:row.id||`variant-${index}`,color,size,stock:Number(row.stock??0),price:row.price==null?product.price:Number(row.price),imageUrl:row.imageUrl||(color?product.colorImages?.[color]:undefined)};});}
 if(colors.length||sizes.length||product.hasVariants===true){const colorOptions=colors.length?colors:['Standard'];const sizeOptions=sizes.length?sizes:['Standard'];return colorOptions.flatMap(color=>sizeOptions.map(size=>({id:`${color}-${size}`,color,size,stock:1,price:product.price,imageUrl:product.colorImages?.[color]})));}
 return[];
}
function variantKey(variant?:ProductVariantSelection):string{return variant?Object.entries(variant).filter(([,value])=>value).sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>`${key}:${value}`).join('|'):'';}
function resolveVisibleProductImage(item:Omit<CartItem,'qty'>):string{if(item.image||item.imageUrl||typeof document==='undefined')return item.image||item.imageUrl||'';const match=Array.from(document.images).find(image=>image.alt.trim().toLowerCase()===item.name.trim().toLowerCase());return match?.currentSrc||match?.src||'';}
export const useCartStore=create<CartState>()(persist((set,get)=>({items:[],isDrawerOpen:false,isMiniCollapsed:false,variantModalProduct:null,variantModalMode:null,addItem:item=>{const resolvedImage=resolveVisibleProductImage(item);const normalized={...item,id:item.id||`${item.productId||''}:${variantKey(item.variant)}`,image:item.image||item.imageUrl||resolvedImage,imageUrl:item.imageUrl||item.image||resolvedImage};set(state=>{const existing=state.items.find(current=>current.id===normalized.id);return{items:existing?state.items.map(current=>current.id===normalized.id?{...current,...normalized,qty:current.qty+1}:current):[...state.items,{...normalized,qty:1}],isDrawerOpen:true,isMiniCollapsed:false};});},removeItem:id=>set(state=>({items:state.items.filter(item=>item.id!==id)})),updateQty:(id,qty)=>set(state=>({items:qty<=0?state.items.filter(item=>item.id!==id):state.items.map(item=>item.id===id?{...item,qty}:item)})),clearCart:()=>set({items:[],isDrawerOpen:false,isMiniCollapsed:false}),openDrawer:()=>set({isDrawerOpen:true,isMiniCollapsed:false}),closeDrawer:()=>set({isDrawerOpen:false}),minimizeCart:()=>set({isDrawerOpen:false,isMiniCollapsed:true}),expandMiniCart:()=>set({isDrawerOpen:true,isMiniCollapsed:false}),toggleDrawer:()=>set(state=>({isDrawerOpen:!state.isDrawerOpen,isMiniCollapsed:state.isDrawerOpen?state.isMiniCollapsed:false})),openVariantModal:(product,mode)=>{if(!variantRows(product).length)return false;set({variantModalProduct:product,variantModalMode:mode});return true;},closeVariantModal:()=>set({variantModalProduct:null,variantModalMode:null}),getCartCount:()=>get().items.reduce((sum,item)=>sum+item.qty,0),getSubtotal:()=>get().items.reduce((sum,item)=>sum+item.price*item.qty,0),getItemsToFreeDelivery:()=>Math.max(0,FREE_DELIVERY_THRESHOLD-get().items.reduce((sum,item)=>sum+item.qty,0)),getDeliveryProgress:()=>Math.min(100,Math.round((get().items.reduce((sum,item)=>sum+item.qty,0)/FREE_DELIVERY_THRESHOLD)*100))}),{name:'phdeals-cart',storage:createJSONStorage(()=>localStorage),partialize:state=>({items:state.items})}));
export function getVariantRows(product:VariantModalProduct):ProductVariantRow[]{return variantRows(product);}
