'use client';
import { ChangeEvent } from 'react';
import { CalendarClock, ClipboardList, Gift, LayoutDashboard, LogOut, MessageCircle, Package, PackageSearch, Search, Settings, Tags, Users, WalletCards, ListChecks, Video } from 'lucide-react';
import type { DashboardStats } from './shared';
export type AdminTab = 'dashboard' | 'settings' | 'products' | 'product-editor' | 'categories' | 'deals' | 'orders' | 'suppliers' | 'rewards' | 'reseller-whatsapp' | 'resellers' | 'reseller-tasks' | 'video-hub';
type Props = { activeTab: AdminTab; onTabChange: (tab: AdminTab) => void; onLogout: () => void; search?: string; onSearchChange?: (value: string) => void; stats?: Partial<DashboardStats> };
const tabs: Array<{ key: AdminTab; label: string; icon: typeof LayoutDashboard }> = [
 { key:'dashboard',label:'Dashboard',icon:LayoutDashboard },{ key:'products',label:'Products',icon:Package },{ key:'product-editor',label:'Product Editor',icon:PackageSearch },{ key:'categories',label:'Categories',icon:Tags },{ key:'deals',label:'One Day Deals',icon:CalendarClock },{ key:'rewards',label:'Rewards',icon:Gift },{ key:'video-hub',label:'Video Hub',icon:Video },{ key:'orders',label:'Orders',icon:ClipboardList },{ key:'reseller-whatsapp',label:'Reseller WA',icon:MessageCircle },{ key:'resellers',label:'Reseller Club',icon:WalletCards },{ key:'reseller-tasks',label:'Reseller Tasks',icon:ListChecks },{ key:'suppliers',label:'Suppliers',icon:Users },{ key:'settings',label:'Settings',icon:Settings },
];
export default function AdminHeader({activeTab,onTabChange,onLogout,search='',onSearchChange,stats}:Props){const searchChanged=(event:ChangeEvent<HTMLInputElement>)=>onSearchChange?.(event.target.value);return <header className="sticky top-0 z-30 border-b border-black/10 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3"><div><h1 className="text-lg font-black">ph<span className="text-[#E1352B]">deals</span> Admin</h1><p className="text-[9px] font-bold text-black/40">{stats?.totalOrders||0} orders · {stats?.totalProducts||0} products</p></div><div className="hidden max-w-xs flex-1 items-center gap-2 rounded-full bg-[#F4F4F1] px-3 py-2 md:flex"><Search size={14}/><input value={search} onChange={searchChanged} placeholder="Search admin data..." className="w-full bg-transparent text-xs outline-none"/></div><button onClick={onLogout} className="flex items-center gap-1 rounded-full bg-[#14140F] px-3 py-2 text-[10px] font-black text-white"><LogOut size={13}/>Logout</button></div><nav className="mx-auto flex max-w-6xl gap-1 overflow-x-auto px-4 pb-3">{tabs.map(({key,label,icon:Icon})=><button key={key} onClick={()=>onTabChange(key)} className={`flex shrink-0 items-center gap-1.5 rounded-full px-3 py-2 text-[10px] font-black ${activeTab===key?'bg-[#E1352B] text-white':'bg-black/5 text-black/55'}`}><Icon size={13}/>{label}</button>)}</nav></header>}
