'use client';
import { useEffect,useState } from 'react';
import { FilePlus2,Loader2,Save } from 'lucide-react';
type BrainFile={id:string;filename:string;title:string;body:string;updated_at?:string};
export default function SalarBrainFiles(){const[files,setFiles]=useState<BrainFile[]>([]);const[selected,setSelected]=useState('');const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');const current=files.find(f=>f.id===selected)||files[0];
async function load(){const r=await fetch('/api/admin/salar/brain',{cache:'no-store',credentials:'same-origin'});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Unable to load brain files.');setFiles(d.files||[]);setSelected((x)=>x||(d.files?.[0]?.id||''));}
useEffect(()=>{void load().catch(e=>setStatus(e.message));},[]);
function patch(key:'title'|'body',value:string){if(!current)return;setFiles(fs=>fs.map(f=>f.id===current.id?{...f,[key]:value}:f));}
async function save(){if(!current)return;setBusy(true);setStatus('');try{const r=await fetch(`/api/admin/salar/brain/${encodeURIComponent(current.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:current.title,body:current.body}),credentials:'same-origin'});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Save failed.');setFiles(fs=>fs.map(f=>f.id===current.id?d.file:f));setStatus('Brain file saved.');}catch(e){setStatus(e instanceof Error?e.message:'Save failed.');}finally{setBusy(false);}}
async function create(){setBusy(true);setStatus('');try{const r=await fetch('/api/admin/salar/brain',{method:'POST',credentials:'same-origin'});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Create failed.');setFiles(fs=>[...fs,d.file]);setSelected(d.file.id);setStatus(`${d.file.filename} created.`);}catch(e){setStatus(e instanceof Error?e.message:'Create failed.');}finally{setBusy(false);}}
return <section className="mt-6 rounded-3xl border border-black/8 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#E1352B]">Training</p><h2 className="text-xl font-black">Brain files</h2><p className="mt-1 text-xs text-black/50">Nayi rule neeche append karein. Website facts Catalogue Refresh se aate hain, yahan sirf dealing/training.</p></div><button onClick={()=>void create()} disabled={busy} className="flex items-center gap-2 rounded-xl bg-[#F4F4F1] px-4 py-3 text-xs font-black"><FilePlus2 size={15}/>New brain file</button></div><div className="mt-4 grid gap-4 md:grid-cols-[210px_1fr]"><div className="space-y-2">{files.map(f=><button key={f.id} onClick={()=>setSelected(f.id)} className={`w-full rounded-xl px-3 py-3 text-left text-xs font-bold ${current?.id===f.id?'bg-[#14140F] text-white':'bg-[#F4F4F1]'}`}><div>{f.filename}</div><div className="mt-1 truncate text-[9px] opacity-60">{f.title}</div></button>)}</div>{current?<div><input value={current.title} onChange={e=>patch('title',e.target.value)} className="w-full rounded-xl border border-black/10 px-3 py-3 text-sm font-bold outline-none"/><textarea value={current.body} onChange={e=>patch('body',e.target.value)} className="mt-3 min-h-[360px] w-full rounded-xl border border-black/10 p-3 font-mono text-xs leading-5 outline-none"/>{current.body.length>80000?<p className="mt-2 rounded-xl bg-[#E1352B]/10 px-3 py-2 text-xs font-bold text-[#E1352B]">file bari hai, New file banayein</p>:null}<div className="mt-3 flex items-center gap-3"><button onClick={()=>void save()} disabled={busy} className="flex items-center gap-2 rounded-xl bg-[#14140F] px-4 py-3 text-xs font-black text-white">{busy?<Loader2 size={15} className="animate-spin"/>:<Save size={15}/>}Save</button><span className="text-[10px] text-black/40">{current.body.length.toLocaleString()} characters</span></div></div>:<div className="text-xs text-black/40">Loading brain file…</div>}</div>{status?<p className="mt-4 rounded-xl bg-[#F4F4F1] px-3 py-3 text-xs font-semibold">{status}</p>:null}</section>}
