'use client';

import { ChangeEvent, FormEvent, useEffect, useRef, useState } from 'react';
import { CheckCircle2, ImagePlus, Loader2, Plus, Trash2, ArrowUp, ArrowDown } from 'lucide-react';
import { getAdminDocument, setAdminDocument, uploadImageToImgBB, createAdminDocument } from './shared';
import type { DailyDeal, PriceBucket } from '@/lib/types';

const DEFAULT_BUCKETS: PriceBucket[] = [
  { id: 'under-99', title: 'Under 99', amount: 99, iconUrl: '', accent: '#E1352B', sortOrder: 1, active: true },
  { id: 'under-299', title: 'Under 299', amount: 299, iconUrl: '', accent: '#D99A17', sortOrder: 2, active: true },
  { id: 'under-999', title: 'Under 999', amount: 999, iconUrl: '', accent: '#0F6A5F', sortOrder: 3, active: true },
  { id: 'premium', title: 'Premium', amount: 999999, iconUrl: '', accent: '#14140F', sortOrder: 4, active: true },
];
const DEFAULT_BIG_DEAL: DailyDeal = { productId: '', imageUrl: '', title: '', originalPrice: 0, dealPrice: 0, startAt: '', endAt: '', buttonText: 'Shop Big Deal', buttonLink: '/deals/big', active: false };
type Settings = { announcementText: string; whatsappNumber: string; freeDeliveryThreshold: number; storePolicyInfo: string; priceBuckets: PriceBucket[]; dailyDeal: DailyDeal };
const DEFAULT_SETTINGS: Settings = { announcementText: '', whatsappNumber: '', freeDeliveryThreshold: 5, storePolicyInfo: '', priceBuckets: DEFAULT_BUCKETS, dailyDeal: DEFAULT_BIG_DEAL };

export default function SiteSettingsManager() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [toast, setToast] = useState(''); const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { getAdminDocument('settings','main').then((snap) => { if (snap.exists()) { const data = snap.data() as Partial<Settings>; setSettings((s) => ({ ...s, ...data, dailyDeal: { ...DEFAULT_BIG_DEAL, ...(data.dailyDeal || {}) }, priceBuckets: Array.isArray(data.priceBuckets) && data.priceBuckets.length ? data.priceBuckets : DEFAULT_BUCKETS })); } }).finally(() => setLoading(false)); }, []);
  const update = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings((s) => ({ ...s, [key]: value }));
  const updateBig = (patch: Partial<DailyDeal>) => update('dailyDeal', { ...settings.dailyDeal, ...patch });
  const updateBucket = (i: number, patch: Partial<PriceBucket>) => update('priceBuckets', settings.priceBuckets.map((b, n) => n === i ? { ...b, ...patch } : b));
  const addBucket = () => update('priceBuckets', [...settings.priceBuckets, { id: `bucket-${Date.now()}`, title: 'New Bucket', amount: 999, iconUrl: '', accent: '#FFB020', sortOrder: settings.priceBuckets.length + 1, active: true }]);
  const removeBucket = (i: number) => update('priceBuckets', settings.priceBuckets.filter((_, n) => n !== i));
  const moveBucket = (i: number, d: -1 | 1) => { const next = [...settings.priceBuckets]; const j = i + d; if (j < 0 || j >= next.length) return; [next[i], next[j]] = [next[j], next[i]]; update('priceBuckets', next.map((b,n) => ({ ...b, sortOrder: n + 1 }))); };
  async function uploadBig(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value=''; if (!file) return; setUploading(true); try { const url = await uploadImageToImgBB(file); updateBig({ imageUrl: url }); await createAdminDocument('media_assets', { name:file.name, url, type:file.type, size:file.size, createdAt:new Date().toISOString(), source:'big-deal' }); setToast('Big Deal image uploaded.'); } catch(e) { setToast(e instanceof Error ? e.message : 'Upload failed.'); } finally { setUploading(false); } }
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d=settings.dailyDeal; if (d.active && (!d.title.trim() || !Number(d.originalPrice) || !Number(d.dealPrice))) { setToast('Big Deal needs title, original price and deal price.'); return; } if (d.active && Number(d.dealPrice) >= Number(d.originalPrice)) { setToast('Big Deal price must be lower than original price.'); return; } setSaving(true); try { await setAdminDocument('settings','main',{ announcementText:settings.announcementText.trim(), whatsappNumber:settings.whatsappNumber.trim(), freeShippingCount:Number(settings.freeDeliveryThreshold||0), freeDelivery:{enabled:true,itemThreshold:Number(settings.freeDeliveryThreshold||0),message:'Add {remaining} more item{plural} to unlock FREE DELIVERY',unlockedMessage:'FREE DELIVERY UNLOCKED 🎉'},storePolicyInfo:settings.storePolicyInfo.trim(),priceBuckets:settings.priceBuckets.map((b,i)=>({...b,sortOrder:i+1,amount:Number(b.amount)||0})),dailyDeal:{...d,title:d.title.trim(),originalPrice:Number(d.originalPrice)||0,dealPrice:Number(d.dealPrice)||0,buttonLink:d.buttonLink.trim()||'/deals/big',buttonText:d.buttonText.trim()||'Shop Big Deal'}}); setToast('Settings and Big Deal saved.'); } catch { setToast('Unable to save settings.'); } finally { setSaving(false); } }
  if (loading) return <div className="mx-auto max-w-4xl px-4 py-6 text-sm text-black/50">Loading site settings...</div>;
  return <section className="mx-auto max-w-5xl px-4 py-6"><h2 className="text-2xl font-black">Store Settings</h2><p className="mt-1 text-sm text-black/55">Header, Big Deal, delivery, price buckets and storefront settings.</p><form onSubmit={save} className="mt-5 space-y-5 rounded-2xl border border-black/10 bg-white p-5">
    <label className="block"><span className="text-xs font-bold">Top Announcement</span><textarea value={settings.announcementText} onChange={e=>update('announcementText',e.target.value)} rows={2} className="mt-1.5 w-full rounded-xl border border-black/15 px-3 py-2.5 text-sm"/></label>
    <label className="block"><span className="text-xs font-bold">WhatsApp Number</span><input value={settings.whatsappNumber} onChange={e=>update('whatsappNumber',e.target.value)} className="mt-1.5 w-full rounded-xl border border-black/15 px-3 py-2.5 text-sm"/></label>
    <label className="block"><span className="text-xs font-bold">Free Delivery Items</span><input type="number" min="0" value={settings.freeDeliveryThreshold} onChange={e=>update('freeDeliveryThreshold',Number(e.target.value))} className="mt-1.5 w-full rounded-xl border border-black/15 px-3 py-2.5 text-sm"/></label>
    <div className="rounded-2xl border border-black/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black">Big Deal Manager</p><p className="mt-1 text-[11px] text-black/45">Separate from Sunday–Saturday deals. Its image, title and prices power the Big Deal hero and detail page.</p></div><label className="flex items-center gap-2 text-xs font-black"><input type="checkbox" checked={settings.dailyDeal.active} onChange={e=>updateBig({active:e.target.checked})}/> Publish</label></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-semibold">Title<input value={settings.dailyDeal.title} onChange={e=>updateBig({title:e.target.value})} placeholder="Big Deal product" className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs font-semibold">Product ID<input value={settings.dailyDeal.productId} onChange={e=>updateBig({productId:e.target.value})} placeholder="Optional product id" className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs font-semibold">Original price<input type="number" min="0" value={settings.dailyDeal.originalPrice||''} onChange={e=>updateBig({originalPrice:Number(e.target.value)})} className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs font-semibold">Big Deal price<input type="number" min="0" value={settings.dailyDeal.dealPrice||''} onChange={e=>updateBig({dealPrice:Number(e.target.value)})} className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs font-semibold">Start time<input type="datetime-local" value={settings.dailyDeal.startAt ? settings.dailyDeal.startAt.slice(0,16) : ''} onChange={e=>updateBig({startAt:e.target.value?new Date(e.target.value).toISOString():''})} className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs font-semibold">End time<input type="datetime-local" value={settings.dailyDeal.endAt ? settings.dailyDeal.endAt.slice(0,16) : ''} onChange={e=>updateBig({endAt:e.target.value?new Date(e.target.value).toISOString():''})} className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label></div>
      <div className="mt-3"><span className="text-xs font-semibold">Hero image</span><div className="mt-1.5 flex items-center gap-2"><button type="button" disabled={uploading} onClick={()=>fileRef.current?.click()} className="inline-flex items-center gap-2 rounded-lg bg-[#14140F] px-3 py-2 text-xs font-black text-white disabled:opacity-50"><ImagePlus size={14}/>{uploading?'Uploading...':'Upload from device'}</button>{settings.dailyDeal.imageUrl&&<img src={settings.dailyDeal.imageUrl} alt="Big Deal preview" className="h-16 w-24 rounded-xl object-cover"/>}</div><input ref={fileRef} type="file" accept="image/*" onChange={uploadBig} className="hidden"/></div>
      <div className="mt-3 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-semibold">Button text<input value={settings.dailyDeal.buttonText} onChange={e=>updateBig({buttonText:e.target.value})} className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label><label className="grid gap-1 text-xs font-semibold">Button link<input value={settings.dailyDeal.buttonLink} onChange={e=>updateBig({buttonLink:e.target.value})} className="rounded-lg border border-black/15 px-3 py-2 text-sm"/></label></div>
    </div>
    <div><div className="mb-3 flex items-center justify-between"><div><p className="text-xs font-bold">Glowing Price Buckets</p><p className="text-[11px] text-black/45">Title, max price, icon, glow accent, order and visibility.</p></div><button type="button" onClick={addBucket} className="inline-flex items-center gap-1 rounded-full bg-[#14140F] px-3 py-2 text-[10px] font-black text-white"><Plus size={13}/>Add</button></div><div className="space-y-2">{settings.priceBuckets.map((b,i)=><div key={b.id} className="grid gap-2 rounded-xl bg-[#F4F4F1] p-3 sm:grid-cols-[1.2fr_100px_1.4fr_90px_72px_80px]"><input value={b.title} onChange={e=>updateBucket(i,{title:e.target.value})} placeholder="Title" className="rounded-lg bg-white px-3 py-2 text-xs"/><input type="number" value={b.amount} onChange={e=>updateBucket(i,{amount:Number(e.target.value)})} placeholder="Max price" className="rounded-lg bg-white px-3 py-2 text-xs"/><input value={b.iconUrl} onChange={e=>updateBucket(i,{iconUrl:e.target.value})} placeholder="Icon image URL" className="rounded-lg bg-white px-3 py-2 text-xs"/><input value={b.accent} onChange={e=>updateBucket(i,{accent:e.target.value})} placeholder="#FFB020" className="rounded-lg bg-white px-3 py-2 text-xs"/><label className="flex items-center gap-2 rounded-lg bg-white px-2 py-2 text-xs font-bold"><input type="checkbox" checked={b.active} onChange={e=>updateBucket(i,{active:e.target.checked})}/>Show</label><div className="flex items-center gap-1"><button type="button" onClick={()=>moveBucket(i,-1)} disabled={i===0} className="rounded-lg bg-white p-2 disabled:opacity-30"><ArrowUp size={13}/></button><button type="button" onClick={()=>moveBucket(i,1)} disabled={i===settings.priceBuckets.length-1} className="rounded-lg bg-white p-2 disabled:opacity-30"><ArrowDown size={13}/></button><button type="button" onClick={()=>removeBucket(i)} className="rounded-lg bg-white p-2 text-[#E1352B]"><Trash2 size={13}/></button></div></div>)}</div></div>
    <label className="block"><span className="text-xs font-bold">Store Policy / Info</span><textarea value={settings.storePolicyInfo} onChange={e=>update('storePolicyInfo',e.target.value)} rows={5} className="mt-1.5 w-full rounded-xl border border-black/15 px-3 py-2.5 text-sm"/></label>
    <button type="submit" disabled={saving||uploading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#14140F] py-3 text-sm font-bold text-white disabled:opacity-50">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:null}{saving?'Saving...':'Save Store Settings'}</button>
  </form>{toast&&<div role="status" className="fixed bottom-5 right-5 z-50 flex max-w-sm items-center gap-2 rounded-xl bg-[#0F6A5F] px-4 py-3 text-sm font-semibold text-white"><CheckCircle2 className="h-4 w-4"/>{toast}</div>}</section>;
}
