'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { collection, doc, getDoc, getDocs } from 'firebase/firestore';
import { ArrowLeft, Check, Clock3, Heart, Minus, Plus, Share2, ShoppingBag, Sparkles, Star, Truck, ShieldCheck, RotateCcw, Headphones } from 'lucide-react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import ReviewsSection from '@/components/ReviewsSection';
import BigDealDiscovery from '@/components/BigDealDiscovery';
import { useSettings } from '@/lib/useSettings';
import { useCartStore } from '@/lib/cartStore';
import { db } from '@/lib/firebase';

type Product={id:string;title?:string;name?:string;price?:number;originalPrice?:number;compareAtPrice?:number;imageUrl?:string;image?:string;images?:string[];category?:string;stock?:number;quantity?:number;isFlashSale?:boolean;rating?:number;reviews?:number;description?:string;[key:string]:any};
type Deal={productId:string;imageUrl:string;title:string;originalPrice:number;dealPrice:number;startAt:string;endAt:string;buttonText:string;buttonLink:string;active:boolean};
const days=[['sunday','Sunday'],['monday','Monday'],['tuesday','Tuesday'],['wednesday','Wednesday'],['thursday','Thursday'],['friday','Friday'],['saturday','Saturday']];
const titleOf=(p:Product)=>p.title||p.name||'PrimeHub Big Deal';
const imageList=(p:Product)=>[...(Array.isArray(p.images)?p.images:[]),p.imageUrl,p.image].filter(Boolean) as string[];
const discountOf=(p:Product,deal?:Deal)=>{const o=Number(deal?.originalPrice??p.originalPrice??p.compareAtPrice??0),v=Number(deal?.dealPrice??p.price??0);return o>v?Math.round(((o-v)/o)*100):0};
const pakistanDay=()=>new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Karachi',weekday:'long'}).format(new Date()).toLowerCase();

function countdown(endAt:string,now:number){const end=new Date(endAt).getTime();if(!end||end<=now)return null;const total=Math.floor((end-now)/1000);return {hours:Math.floor(total/3600),minutes:Math.floor((total%3600)/60),seconds:total%60};}

export default function BigDealPage(){
 const router=useRouter(); const {settings,loading:settingsLoading}=useSettings(); const deal=settings.dailyDeal as Deal|undefined;
 const [product,setProduct]=useState<Product|null>(null),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[activeImage,setActiveImage]=useState(0),[quantity,setQuantity]=useState(1),[wished,setWished]=useState(false),[added,setAdded]=useState(false),[now,setNow]=useState(Date.now());
 const addItem=useCartStore(s=>s.addItem);
 useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{let cancelled=false;async function load(){if(!deal?.productId){setLoading(false);return}setLoading(true);try{const [featuredSnap,allSnap]=await Promise.all([getDoc(doc(db,'products',deal.productId)),getDocs(collection(db,'products'))]);if(cancelled)return;setProduct(featuredSnap.exists()?{id:featuredSnap.id,...featuredSnap.data()} as Product:null);setProducts(allSnap.docs.map(d=>({id:d.id,...d.data()} as Product)))}catch{if(!cancelled){setProduct(null);setProducts([])}}finally{if(!cancelled)setLoading(false)}}load();return()=>{cancelled=true}},[deal?.productId]);
 const images=useMemo(()=>product?imageList(product):deal?.imageUrl?[deal.imageUrl]:[],[product,deal?.imageUrl]); const price=Number(deal?.dealPrice??product?.price??0); const original=Number(deal?.originalPrice??product?.originalPrice??product?.compareAtPrice??0); const discount=product?discountOf(product,deal):original>price?Math.round(((original-price)/original)*100):0; const timer=deal?.endAt?countdown(deal.endAt,now):null; const stockKnown=Boolean(product&&Object.prototype.hasOwnProperty.call(product,'stock')); const stock=stockKnown?Number(product?.stock):0; const maxQuantity=stockKnown&&stock>0?stock:20; const weekly=(settings.weeklyDeals||[]).filter(x=>x.active!==false); const currentDay=pakistanDay();
 const addToCart=()=>{if(!product)return;const image=images[0]||'';for(let i=0;i<quantity;i++)addItem({id:product.id,name:titleOf(product),price,originalPrice:original||price,image,imageUrl:image});setAdded(true);window.setTimeout(()=>setAdded(false),1200)};
 const buyNow=()=>{addToCart();router.push('/checkout')};
 const share=async()=>{if(typeof navigator!=='undefined'&&navigator.share)await navigator.share({title:titleOf(product||{}),url:window.location.href}).catch(()=>{});else if(typeof navigator!=='undefined'&&navigator.clipboard)await navigator.clipboard.writeText(window.location.href)};
 if(settingsLoading||loading)return <><Header/><main className="min-h-screen bg-[#F4F4F1] px-4 py-6"><div className="mx-auto max-w-6xl animate-pulse"><div className="h-5 w-28 rounded bg-black/8"/><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="aspect-square rounded-[30px] bg-white"/><div className="rounded-[30px] bg-white p-8"><div className="h-7 w-3/4 rounded bg-black/8"/><div className="mt-5 h-10 w-1/3 rounded bg-black/8"/><div className="mt-8 h-24 rounded bg-black/8"/></div></div></div></main><Footer/></>;
 if(!deal?.active||!deal.title)return <><Header/><main className="min-h-screen bg-[#F4F4F1] px-4 py-8"><div className="mx-auto max-w-4xl rounded-[30px] bg-white p-10 text-center shadow-sm"><Sparkles className="mx-auto h-10 w-10 text-[#FFB020]"/><h1 className="mt-4 text-2xl font-black">Big Deal is not active</h1><p className="mt-1 text-xs text-black/45">The next Big Deal can be published from Admin → Settings.</p><Link href="/" className="mt-5 inline-flex rounded-full bg-[#14140F] px-5 py-3 text-[10px] font-black text-white">Back to Deals</Link></div></main><Footer/></>;
 return <><Header/><main className="min-h-screen bg-[#F4F4F1] pb-32"><div className="mx-auto max-w-6xl px-4 py-4 md:px-6"><div className="flex items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-[10px] font-black shadow-sm"><ArrowLeft size={14}/>Home</Link><span className="text-[9px] font-black uppercase tracking-[.2em] text-black/35">Premium Big Deal</span></div>
 <div className="mt-4 text-xs text-black/40">Home <span className="mx-1">/</span> Big Deal <span className="mx-1">/</span> <span className="font-bold text-black/65">{deal.title}</span></div>
 <section className="mt-4 overflow-hidden rounded-[32px] border border-black/7 bg-white shadow-[0_18px_55px_rgba(20,20,15,.08)]"><div className="grid md:grid-cols-[1.05fr_.95fr]"><div className="relative bg-[#F4F4F1] md:min-h-[620px]"><div className="relative aspect-square h-full overflow-hidden md:aspect-auto">{images[activeImage]?<img src={images[activeImage]} alt={deal.title} className="h-full w-full object-cover"/>:<div className="flex h-full min-h-[420px] items-center justify-center text-sm font-bold text-black/25">No product image</div>}<div className="absolute left-4 top-4 flex flex-wrap gap-2"><span className="rounded-full bg-[#14140F] px-3 py-1.5 text-[9px] font-black uppercase tracking-wider text-white">BIG DEAL</span>{discount>0&&<span className="rounded-full bg-[#FFB020] px-3 py-1.5 text-[9px] font-black text-[#14140F]">-{discount}% OFF</span>}</div>{images.length>1&&<div className="absolute bottom-4 left-4 right-4 flex gap-2 overflow-x-auto">{images.map((img,i)=><button key={`${img}-${i}`} type="button" onClick={()=>setActiveImage(i)} className={`h-16 w-16 shrink-0 overflow-hidden rounded-xl border-2 bg-white ${i===activeImage?'border-[#E1352B]':'border-transparent'}`}><img src={img} alt="" className="h-full w-full object-cover"/></button>)}</div>}</div></div>
 <div className="flex flex-col p-6 md:p-10"><div className="flex items-center justify-between gap-3"><span className="text-[9px] font-black uppercase tracking-[.2em] text-[#E1352B]">Limited time offer</span><div className="flex gap-2"><button type="button" onClick={()=>setWished(v=>!v)} aria-label="Wishlist" className="flex h-10 w-10 items-center justify-center rounded-full border border-black/8 bg-white"><Heart size={16} className={wished?'text-[#E1352B]':'text-[#14140F]'} fill={wished?'currentColor':'none'}/></button><button type="button" onClick={share} aria-label="Share deal" className="flex h-10 w-10 items-center justify-center rounded-full border border-black/8 bg-white"><Share2 size={16}/></button></div></div><h1 className="mt-3 text-3xl font-black leading-tight tracking-tight md:text-4xl">{deal.title}</h1>{product&&(Number(product.rating)>0||Number(product.reviews)>0)&&<div className="mt-3 flex items-center gap-2"><span className="flex items-center gap-1 rounded-full bg-[#FFB020]/15 px-2.5 py-1.5 text-[10px] font-black"><Star size={11} fill="currentColor"/>{Number(product.rating||0).toFixed(1)}</span>{Number(product.reviews)>0&&<span className="text-[10px] font-bold text-black/40">{Number(product.reviews).toLocaleString()} reviews</span>}</div>}<div className="mt-5 flex flex-wrap items-end gap-2"><span className="text-3xl font-black text-[#E1352B]">Rs. {price.toLocaleString()}</span>{original>price&&<span className="mb-1 text-sm text-black/35 line-through">Rs. {original.toLocaleString()}</span>}</div>{discount>0&&<p className="mt-1 text-[10px] font-black uppercase tracking-wider text-[#0F6A5F]">You save Rs. {(original-price).toLocaleString()}</p>}
 <div className="mt-5 rounded-2xl border border-[#E1352B]/15 bg-[#FFF8F6] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#E1352B]">Offer countdown</p><p className="mt-1 text-[10px] text-black/45">Based on the real Admin deal expiry.</p></div>{timer?<div className="flex items-center gap-1.5 font-mono text-lg font-black text-[#14140F]"><Clock3 size={15}/>{String(timer.hours).padStart(2,'0')}:{String(timer.minutes).padStart(2,'0')}:{String(timer.seconds).padStart(2,'0')}</div>:<span className="text-[10px] font-black text-black/45">No expiry configured</span>}</div></div>
 {stockKnown&&<p className="mt-3 text-[10px] font-black text-[#0F6A5F]">{stock>0?`${stock} available`:'Currently out of stock'}</p>}
 {product?.description&&<div className="mt-5"><h2 className="text-[10px] font-black uppercase tracking-[.16em]">Product details</h2><p className="mt-2 whitespace-pre-line text-xs leading-5 text-black/55">{product.description}</p></div>}
 <div className="mt-6 flex items-center justify-between rounded-2xl border border-black/8 p-2"><span className="pl-2 text-[10px] font-black uppercase tracking-wider text-black/40">Quantity</span><div className="flex items-center rounded-xl bg-[#F4F4F1]"><button type="button" onClick={()=>setQuantity(q=>Math.max(1,q-1))} className="flex h-10 w-10 items-center justify-center"><Minus size={14}/></button><span className="w-8 text-center text-xs font-black">{quantity}</span><button type="button" onClick={()=>setQuantity(q=>Math.min(maxQuantity,q+1))} disabled={stockKnown&&stock<1} className="flex h-10 w-10 items-center justify-center disabled:opacity-30"><Plus size={14}/></button></div></div>
 <div className="mt-4 grid gap-2 sm:grid-cols-2"><button type="button" onClick={addToCart} disabled={stockKnown&&stock<1} className="flex items-center justify-center gap-2 rounded-2xl bg-[#14140F] py-4 text-xs font-black text-white transition hover:bg-[#E1352B] disabled:opacity-40">{added?<><Check size={15}/>Added to Cart</>:<><ShoppingBag size={15}/>Add to Cart</>}</button><button type="button" onClick={buyNow} disabled={stockKnown&&stock<1} className="flex items-center justify-center gap-2 rounded-2xl bg-[#E1352B] py-4 text-xs font-black text-white disabled:opacity-40">Buy Now</button></div><p className="mt-2 text-center text-[9px] font-bold text-black/35">Uses the existing PrimeHub cart and checkout flow.</p></div></div></section>
 <section className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4"><div className="rounded-2xl bg-white p-4"><Truck size={17} className="text-[#0F6A5F]"/><p className="mt-2 text-[10px] font-black">Delivery</p><p className="mt-1 text-[9px] leading-4 text-black/40">See available delivery options at checkout.</p></div><div className="rounded-2xl bg-white p-4"><ShieldCheck size={17} className="text-[#0F6A5F]"/><p className="mt-2 text-[10px] font-black">Secure checkout</p><p className="mt-1 text-[9px] leading-4 text-black/40">Checkout uses the existing PrimeHub order flow.</p></div><div className="rounded-2xl bg-white p-4"><RotateCcw size={17} className="text-[#0F6A5F]"/><p className="mt-2 text-[10px] font-black">Returns</p><p className="mt-1 text-[9px] leading-4 text-black/40">Refer to PrimeHub's configured return policy.</p></div><div className="rounded-2xl bg-white p-4"><Headphones size={17} className="text-[#0F6A5F]"/><p className="mt-2 text-[10px] font-black">Support</p><p className="mt-1 text-[9px] leading-4 text-black/40">Contact support through the existing site channels.</p></div></section>
 {product&&<section className="mt-10"><ReviewsSection productId={product.id}/></section>}
 {weekly.length>0&&<section className="mt-10"><div className="mb-4"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#0F6A5F]">Admin-managed deals</p><h2 className="mt-1 text-2xl font-black">Weekly Deals</h2></div><div className="flex gap-2 overflow-x-auto pb-2 [scrollbar-width:none]">{days.map(([key,label])=>{const dealForDay=weekly.find(d=>d.day===key);const active=key===currentDay;return <Link key={key} href={dealForDay?.buttonLink||`/deals/${key}`} className={`min-w-[112px] overflow-hidden rounded-[20px] border bg-white ${active?'border-[#0F6A5F] ring-2 ring-[#0F6A5F]/10':'border-black/7'}`}><div className="relative aspect-[4/3] bg-[#F4F4F1]">{dealForDay?.imageUrl?<img src={dealForDay.imageUrl} alt={dealForDay.title} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-[#0F6A5F]"><Sparkles size={18}/></div>}{active&&<span className="absolute right-1.5 top-1.5 rounded-full bg-[#0F6A5F] px-1.5 py-1 text-[7px] font-black text-white">TODAY</span>}</div><div className="p-2.5"><p className="text-[9px] font-black uppercase">{label}</p>{dealForDay?<><p className="mt-1 line-clamp-2 text-[9px] font-bold text-black/55">{dealForDay.title}</p><p className="mt-1 text-[10px] font-black text-[#E1352B]">Rs. {Number(dealForDay.dealPrice).toLocaleString()}</p></>:<p className="mt-1 text-[8px] font-bold text-black/30">No deal published</p>}</div></Link>})}</div></section>}
 <BigDealDiscovery products={products} weeklyDeals={weekly} featuredProductId={deal.productId}/>
 </div></main><Footer/></>;
}
