'use client';
import { Tag } from 'lucide-react';
import { DAYS, type ProductDealSettingsProps } from './ProductTypes';
export default function ProductDealSettings({deal,priceBuckets,bucketIds,onDealChange,onBucketToggle}: ProductDealSettingsProps) {
  const selectedDealLabel=deal.day==='big'?'Big Deal':deal.day?DAYS.find(item=>item.key===deal.day)?.label:'No deal — regular product';
  return <>
    <div className="rounded-2xl border border-[#FFB020]/30 bg-[#FFF9E9] p-4"><div className="flex items-center gap-2"><Tag size={16} className="text-[#D99A17]"/><div><p className="text-sm font-black">Deal placement</p><p className="text-[11px] text-black/50">Choose a day, Big Deal, or leave as regular product.</p></div></div><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="grid gap-1"><span className="text-[10px] font-black uppercase tracking-wider text-black/45">Which deal?</span><select value={deal.day} onChange={e=>onDealChange({day:e.target.value as ProductDealSettingsProps['deal']['day'],dealPrice:e.target.value?deal.dealPrice:''})} className="rounded-xl bg-white p-3 text-sm"><option value="">None — regular product</option><option value="big">Big Deal</option>{DAYS.map(day=><option key={day.key} value={day.key}>{day.label}</option>)}</select></label><label className={!deal.day?'grid gap-1 opacity-40':'grid gap-1'}><span className="text-[10px] font-black uppercase tracking-wider text-black/45">Deal price</span><input disabled={!deal.day} value={deal.dealPrice} onChange={e=>onDealChange({...deal,dealPrice:e.target.value})} type="number" min="1" placeholder="Rs. 1,299" className="rounded-xl bg-white p-3 text-sm"/></label></div><p className="mt-3 text-[10px] font-bold text-black/45">Selected: {selectedDealLabel}</p></div>
    <div className="rounded-2xl border border-black/10 bg-[#FAFAF7] p-4"><div className="flex items-center gap-2"><Tag size={15} className="text-[#0F6A5F]"/><p className="text-sm font-black">Price Buckets</p></div>{!priceBuckets.length?<p className="mt-3 rounded-xl bg-white p-3 text-xs text-black/45">No active price buckets.</p>:<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{priceBuckets.map(bucket=><label key={bucket.id} className={`flex cursor-pointer items-center gap-2 rounded-xl bg-white p-3 text-xs font-bold ring-1 ${bucketIds.includes(bucket.id)?'ring-[#0F6A5F]':'ring-black/5'}`}><input type="checkbox" checked={bucketIds.includes(bucket.id)} onChange={e=>onBucketToggle(bucket.id,e.target.checked)}/><span>{bucket.title}</span></label>)}</div>}{!!bucketIds.length&&<p className="mt-2 text-[10px] font-bold text-black/45">Assigned: {bucketIds.map(id=>priceBuckets.find(bucket=>bucket.id===id)?.title||id).join(' · ')}</p>}</div>
  </>;
}
