'use client';
import { Loader2 } from 'lucide-react';
import ProductDealSettings from './ProductDealSettings';
import ProductGallery from './ProductGallery';
import ProductVariants from './ProductVariants';
import type { ProductFormProps } from './ProductTypes';
export default function ProductForm(props: ProductFormProps) {
  const {form,categories,priceBuckets,deal,bucketIds,colors,colorDraft,sizes,customSize,variantRows,busy,uploadingSlot,uploadingColor,editing,showGallery,gallerySearch,gallery,onSubmit,onChange,onUpload,onSetMainImage,onRemoveImage,onColorDraftChange,onColorKeyDown,onAddColor,onRemoveColor,onSetColorImage,onUploadColorPhoto,onToggleSize,onCustomSizeChange,onCustomSizeKeyDown,onAddCustomSize,onRemoveVariantRow,onUpdateVariantStock,onDealChange,onBucketToggle,onGallerySearchChange,onToggleGallery,onReset}=props;
  return <form onSubmit={onSubmit} className="mt-5 grid gap-4 rounded-3xl bg-white p-5 shadow-sm">
    <ProductGallery form={form} busy={busy} uploadingSlot={uploadingSlot} showGallery={showGallery} gallerySearch={gallerySearch} gallery={gallery} onUpload={onUpload} onSetMainImage={onSetMainImage} onRemoveImage={onRemoveImage} onGallerySearchChange={onGallerySearchChange} onToggleGallery={onToggleGallery} onChangeImages={images=>onChange('images',images)}/>
    <div className="grid gap-3 md:grid-cols-2"><input value={form.title} onChange={e=>onChange('title',e.target.value)} placeholder="Product name" required className="rounded-xl bg-[#F4F4F1] p-3 text-sm md:col-span-2"/><label className="grid gap-1"><span className="text-[10px] font-black uppercase tracking-wider text-black/45">Original price</span><input value={form.originalPrice} onChange={e=>onChange('originalPrice',e.target.value)} type="number" min="0" required className="rounded-xl bg-[#F4F4F1] p-3 text-sm"/></label><label className="grid gap-1"><span className="text-[10px] font-black uppercase tracking-wider text-black/45">Discount price</span><input value={form.discountPrice} onChange={e=>onChange('discountPrice',e.target.value)} type="number" min="0" placeholder="Optional" className="rounded-xl bg-[#F4F4F1] p-3 text-sm"/></label><label className="grid gap-1"><span className="text-[10px] font-black uppercase tracking-wider text-black/45">Category</span><select value={form.category} onChange={e=>onChange('category',e.target.value)} required className="rounded-xl bg-[#F4F4F1] p-3 text-sm"><option value="">Select category</option>{categories.map(category=><option key={category.id} value={category.id}>{category.title}</option>)}</select></label><label className="grid gap-1"><span className="text-[10px] font-black uppercase tracking-wider text-black/45">Stock quantity</span><input value={form.stock} onChange={e=>onChange('stock',e.target.value)} type="number" min="0" className="rounded-xl bg-[#F4F4F1] p-3 text-sm"/></label><input value={form.videoUrl} onChange={e=>onChange('videoUrl',e.target.value)} placeholder="YouTube Shorts / Reels / MP4 URL (optional)" className="rounded-xl bg-[#F4F4F1] p-3 text-sm md:col-span-2"/></div>
    <textarea value={form.description} onChange={e=>onChange('description',e.target.value)} placeholder="Product description" className="min-h-32 rounded-xl bg-[#F4F4F1] p-3 text-sm"/>
    <ProductVariants form={form} colors={colors} colorDraft={colorDraft} sizes={sizes} customSize={customSize} variantRows={variantRows} uploadingColor={uploadingColor} onColorDraftChange={onColorDraftChange} onColorKeyDown={onColorKeyDown} onAddColor={onAddColor} onRemoveColor={onRemoveColor} onSetColorImage={onSetColorImage} onUploadColorPhoto={onUploadColorPhoto} onToggleSize={onToggleSize} onCustomSizeChange={onCustomSizeChange} onCustomSizeKeyDown={onCustomSizeKeyDown} onAddCustomSize={onAddCustomSize} onRemoveVariantRow={onRemoveVariantRow} onUpdateVariantStock={onUpdateVariantStock}/>
    <ProductDealSettings deal={deal} priceBuckets={priceBuckets} bucketIds={bucketIds} onDealChange={onDealChange} onBucketToggle={onBucketToggle}/>
    <div className="rounded-2xl border border-black/10 bg-[#FAFAF7] p-4 flex flex-wrap gap-5 text-xs font-bold"><label className="flex items-center gap-2"><input type="checkbox" checked={form.published} onChange={e=>onChange('published',e.target.checked)}/> Published on storefront</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.featured} onChange={e=>onChange('featured',e.target.checked)}/> Featured product</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.isWholesale} onChange={e=>onChange('isWholesale',e.target.checked)}/> Wholesale badge</label></div>
    <div className="flex gap-2"><button type="submit" disabled={busy} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#14140F] py-3 text-xs font-black text-white disabled:opacity-50">{busy&&<Loader2 size={14} className="animate-spin"/>}{editing?'Save product':'Add product'}</button>{editing&&<button type="button" onClick={onReset} className="rounded-xl bg-black/5 px-5 text-xs font-black">Cancel</button>}</div>
  </form>;
}
