'use client';
import { ImagePlus, Loader2, Plus, Trash2, X } from 'lucide-react';
import { QUICK_SIZES, type ProductVariantsProps } from './ProductTypes';
export default function ProductVariants({form,colors,colorDraft,sizes,customSize,variantRows,uploadingColor,onColorDraftChange,onColorKeyDown,onAddColor,onRemoveColor,onSetColorImage,onUploadColorPhoto,onToggleSize,onCustomSizeChange,onCustomSizeKeyDown,onAddCustomSize,onRemoveVariantRow,onUpdateVariantStock}: ProductVariantsProps) {
  return <>
    <div className="rounded-2xl border border-[#0F6A5F]/15 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-base font-black">Bangles Variants</p><p className="text-[11px] text-black/45">Add colors and sizes here. No nested option fields.</p></div><div className="flex w-full gap-2 sm:w-auto"><input value={colorDraft} onChange={e=>onColorDraftChange(e.target.value)} onKeyDown={onColorKeyDown} placeholder="Enter Color (e.g. Red, Golden, Maroon)" className="min-w-0 flex-1 rounded-xl border border-black/10 bg-[#FAFAF7] p-3 text-xs sm:w-72"/><button type="button" onClick={onAddColor} className="inline-flex shrink-0 items-center gap-1 rounded-xl bg-[#0F6A5F] px-4 py-3 text-xs font-black text-white"><Plus size={14}/> Add Color</button></div></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-2">{colors.map(color=><div key={color.id} className="rounded-2xl border border-black/8 bg-[#FAFAF7] p-3"><div className="flex items-center gap-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-white ring-1 ring-black/5">{color.imageUrl?<img src={color.imageUrl} alt={color.name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-black/15"><ImagePlus size={18}/></div>}</div><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-wider text-black/35">Color</p><p className="truncate text-sm font-black">{color.name}</p></div><button type="button" onClick={()=>onRemoveColor(color.id)} className="rounded-lg bg-red-50 p-2 text-[#E1352B]" aria-label={`Delete ${color.name}`}><X size={14}/></button></div><div className="mt-3 flex flex-wrap gap-2"><select value={form.images.includes(color.imageUrl)?color.imageUrl:''} onChange={e=>onSetColorImage(color.id,e.target.value)} className="min-w-0 flex-1 rounded-lg bg-white p-2 text-[10px]"><option value="">Attach product image…</option>{form.images.map((url,index)=><option key={url} value={url}>Product image {index+1}</option>)}{color.imageUrl&&!form.images.includes(color.imageUrl)&&<option value={color.imageUrl}>Uploaded color photo</option>}</select><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-[#14140F] px-3 py-2 text-[10px] font-black text-white">{uploadingColor===color.id?<Loader2 size={12} className="animate-spin"/>:<ImagePlus size={12}/>} Attach/Upload Image<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={e=>onUploadColorPhoto(color.id,e)}/></label></div></div>)}</div>{!colors.length&&<div className="mt-4 rounded-xl bg-[#FAFAF7] p-5 text-center text-xs text-black/35">No colors added yet. Enter a color above to begin.</div>}
    </div>
    <div className="rounded-2xl border border-black/10 bg-white p-4"><div><p className="text-base font-black">Bangle Sizes</p><p className="text-[11px] text-black/45">Click a chip to turn a size on or off.</p></div><div className="mt-3 flex flex-wrap gap-2">{QUICK_SIZES.map(size=><button type="button" key={size} onClick={()=>onToggleSize(size)} className={`rounded-full px-4 py-2.5 text-xs font-black transition ${sizes.includes(size)?'bg-[#0F6A5F] text-white shadow-sm':'bg-[#F4F4F1] text-black/60'}`}>{sizes.includes(size)?'✓ ':''}{size}</button>)}</div><div className="mt-3 flex gap-2"><input value={customSize} onChange={e=>onCustomSizeChange(e.target.value)} onKeyDown={onCustomSizeKeyDown} placeholder="Custom Size" className="min-w-0 flex-1 rounded-xl bg-[#F4F4F1] p-3 text-xs"/><button type="button" onClick={onAddCustomSize} className="rounded-xl bg-[#14140F] px-4 text-xs font-black text-white"><Plus size={13} className="mr-1 inline"/> Add</button></div>{sizes.filter(size=>!QUICK_SIZES.includes(size)).length>0&&<div className="mt-3 flex flex-wrap gap-2">{sizes.filter(size=>!QUICK_SIZES.includes(size)).map(size=><button type="button" key={size} onClick={()=>onToggleSize(size)} className="rounded-full bg-[#0F6A5F] px-3 py-1.5 text-[10px] font-black text-white">✓ {size} ×</button>)}</div>}</div>
    {colors.length>0&&sizes.length>0&&<div className="rounded-2xl border border-black/10 bg-white p-4"><div className="flex items-center justify-between gap-2"><div><p className="text-base font-black">Auto-Generated Variants</p><p className="text-[11px] text-black/45">Rows update automatically as colors and sizes change.</p></div><span className="rounded-full bg-[#0F6A5F]/10 px-3 py-1.5 text-[10px] font-black text-[#0F6A5F]">{variantRows.length} combinations</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead><tr className="border-b border-black/10 text-[9px] uppercase tracking-wider text-black/40"><th className="p-2">Color Image</th><th className="p-2">Color</th><th className="p-2">Size</th><th className="p-2">Stock</th><th className="p-2 text-right">Remove</th></tr></thead><tbody>{variantRows.map(row=><tr key={row.id} className="border-b border-black/5"><td className="p-2"><div className="h-11 w-11 overflow-hidden rounded-xl bg-[#F4F4F1]">{row.imageUrl?<img src={row.imageUrl} alt="" className="h-full w-full object-cover"/>:null}</div></td><td className="p-2 font-black">{row.color}</td><td className="p-2 font-semibold">{row.size}</td><td className="p-2"><input type="number" min="0" value={row.stock} onChange={e=>onUpdateVariantStock(row.id,e.target.value)} className="w-24 rounded-lg bg-[#F4F4F1] p-2"/></td><td className="p-2 text-right"><button type="button" onClick={()=>onRemoveVariantRow(row.id)} className="rounded-lg bg-red-50 p-2 text-[#E1352B]" aria-label="Remove variant"><Trash2 size={13}/></button></td></tr>)}</tbody></table></div></div>}
  </>;
}
