'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Banknote, CheckCircle2, Gift, RefreshCw, ShieldCheck, Trophy, Users, WalletCards, XCircle } from 'lucide-react';
import { auth } from '@/lib/firebase';

const money = (v: unknown) => `Rs. ${Number(v || 0).toLocaleString()}`;

export default function AdminResellersPage() {
  const [data, setData] = useState<any>({ stats: {}, profiles: [], withdrawals: [], ledger: [] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const user = auth.currentUser; if (!user) throw new Error('Admin session is not available. Please sign in again.'); const token = await user.getIdToken(); const r = await fetch('/api/admin/reseller-management', { headers: { Authorization: `Bearer ${token}` }, cache: 'no-store' }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Unable to load reseller data.'); setData(d); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load reseller data.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  async function review(id: string, action: 'approve' | 'reject' | 'paid') { setBusy(`${id}:${action}`); setError(''); try { const user = auth.currentUser; if (!user) throw new Error('Admin session is not available.'); const token = await user.getIdToken(); const r = await fetch('/api/admin/reseller-management', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ id, action }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Action failed.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Action failed.'); } finally { setBusy(''); } }
  const s = data.stats || {};
  return <main className="min-h-screen bg-[#F4F4F1] text-[#14140F]"><section className="bg-[#14140F] px-4 py-7 text-white sm:px-6"><div className="mx-auto max-w-6xl"><Link href="/admin" className="inline-flex items-center gap-2 text-[10px] font-bold text-white/60"><ArrowLeft size={13}/> Admin</Link><div className="mt-5 flex items-center justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[0.2em] text-[#FFCF68]">PrimeHub Control</p><h1 className="mt-1 text-2xl font-black">Reseller Management</h1><p className="mt-1 text-[10px] text-white/45">Live members, rewards, wallets and withdrawals.</p></div><button onClick={load} className="rounded-full bg-white/10 p-3" aria-label="Refresh"><RefreshCw size={17}/></button></div></div></section>
  <section className="mx-auto max-w-6xl space-y-5 px-4 py-6 sm:px-6">{error&&<div className="rounded-2xl bg-[#E1352B]/10 p-3 text-[10px] font-bold text-[#B82B23]">{error}</div>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat title="Active Resellers" value={s.resellers || 0} icon={Users}/><Stat title="Pending Withdrawals" value={s.pendingWithdrawals || 0} icon={Banknote}/><Stat title="Wallet Liability" value={money(s.walletLiability)} icon={WalletCards}/><Stat title="Rewards Recorded" value={money(s.totalRewards)} icon={Gift}/></div>
  <div className="grid gap-4 lg:grid-cols-2"><Panel title="Tier Rules" icon={<Trophy size={16}/>} rows={['Starter · 5 orders · 5%', 'Prime · 10 orders · 10%', 'Pro · 20 orders · 15%', 'Elite · 30 orders · 20%']} /><Panel title="Reward & Withdrawal" icon={<WalletCards size={16}/>} rows={['Minimum withdrawal · Rs. 500', 'Eligible reward · Delivered orders', 'Reward · Pending → Available', 'Payout · Admin approval']} /></div>
  <section className="rounded-[26px] bg-white p-5 shadow-[0_10px_28px_rgba(20,20,15,0.05)]"><div className="flex items-center justify-between"><h2 className="text-sm font-black">Withdrawal Requests</h2><span className="text-[9px] font-black text-black/35">{data.withdrawals.length} total</span></div><div className="mt-4 space-y-3">{loading?<p className="text-[10px] text-black/40">Loading live data…</p>:data.withdrawals.length===0?<p className="rounded-xl bg-[#F4F4F1] p-4 text-[10px] text-black/40">No withdrawal requests yet.</p>:data.withdrawals.map((w:any)=><div key={w.id} className="rounded-2xl border border-black/5 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-black">{money(w.amount)}</p><p className="mt-1 text-[10px] text-black/45">{w.method}{w.bankName?` · ${w.bankName}`:''} · {w.accountTitle} · {w.accountNumber}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-wider text-black/30">{w.status} · {w.userId}</p></div><div className="flex gap-2">{w.status==='pending'&&<><button disabled={!!busy} onClick={()=>review(w.id,'approve')} className="rounded-xl bg-[#0F6A5F] px-3 py-2 text-[9px] font-black text-white">{busy===`${w.id}:approve`?'…':'Approve'}</button><button disabled={!!busy} onClick={()=>review(w.id,'reject')} className="rounded-xl bg-[#E1352B]/10 px-3 py-2 text-[9px] font-black text-[#B82B23]">{busy===`${w.id}:reject`?'…':'Reject'}</button></>}{w.status==='approved'&&<button disabled={!!busy} onClick={()=>review(w.id,'paid')} className="rounded-xl bg-[#14140F] px-3 py-2 text-[9px] font-black text-white">{busy===`${w.id}:paid`?'…':'Mark Paid'}</button>}</div></div></div>)}</div></section>
  <section className="rounded-[26px] bg-white p-5 shadow-[0_10px_28px_rgba(20,20,15,0.05)]"><h2 className="text-sm font-black">Reseller Members</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{data.profiles.length===0?<p className="text-[10px] text-black/40">No reseller profiles yet.</p>:data.profiles.map((p:any)=><div key={p.id} className="rounded-2xl bg-[#F4F4F1] p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-black">{p.displayName||p.email||p.id}</p><span className="rounded-full bg-white px-2 py-1 text-[8px] font-black uppercase">{p.tierId||'starter'}</span></div><p className="mt-1 text-[9px] text-black/40">Orders: {p.monthlyOrders||0} · Available: {money(p.walletAvailable)} · Pending: {money(p.walletPending)}</p></div>)}</div></section>
  <div className="rounded-[24px] border border-[#0F6A5F]/10 bg-[#0F6A5F]/5 p-4 text-[10px] leading-5 text-black/50"><div className="flex items-center gap-2 font-black text-[#14140F]"><ShieldCheck size={15} className="text-[#0F6A5F]"/> Admin-only control</div><p className="mt-1">All live reseller reads and payout actions go through the server-side admin API. Resellers cannot approve, reject or mark their own withdrawals as paid.</p></div></section></main>;
}

function Stat({title,value,icon:Icon}:{title:string;value:any;icon:any}){return <div className="rounded-[24px] bg-white p-4 shadow-[0_10px_28px_rgba(20,20,15,0.05)]"><Icon size={18} className="text-[#0F6A5F]"/><p className="mt-3 text-[9px] font-black uppercase tracking-wider text-black/35">{title}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function Panel({title,icon,rows}:{title:string;icon:React.ReactNode;rows:string[]}){return <div className="rounded-[26px] bg-white p-5 shadow-[0_10px_28px_rgba(20,20,15,0.05)]"><div className="flex items-center gap-2 text-sm font-black text-[#0F6A5F]">{icon}<span className="text-[#14140F]">{title}</span></div><div className="mt-3 space-y-2">{rows.map(row=><div key={row} className="rounded-xl bg-[#F4F4F1] px-3 py-2.5 text-[10px] font-semibold">{row}</div>)}</div></div>}

